/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";
export * from "./models";

// SMH Client - 提供集中管理和网络请求重试功能
export { SMHClient, SMHClientOptions, type OnTokenRefresh } from "./interceptor/SmhClient";

// Loaders - 文件上传/下载器
export {
  Uploader,
  Downloader,
  CommonLoader,
  TaskStatus,
  type IFile,
  type ProgressInfo,
  type IUpPartInfo,
  type UploadCheckpoint,
  type UploadOptions,
  type IDownPartInfo,
  type DownloadCheckpoint,
  type DownloadOptions,
  type UrlDownloadOptions,
  type IRemoteFile
} from "./loaders";

// Utils - 工具模块
export {
  SMHError,
  ErrorCode,
  ServerErrorCode,
  newError,
  getServerErrorMessage,
  setServerErrorMessages,
  resetServerErrorMessages,
  wrapErrorToSMHError,
  setErrorLocale,
  getErrorLocale,
  EventEmitter,
  formatSize,
  formatTime,
  formatRemainingTime,
  parallelLimit
} from "./utils";
