/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BatchCopy200Response } from '../models';
// @ts-ignore
import type { BatchCopy202Response } from '../models';
// @ts-ignore
import type { BatchCopy207Response } from '../models';
// @ts-ignore
import type { BatchCopyRequestInner } from '../models';
// @ts-ignore
import type { BatchDelete200Response } from '../models';
// @ts-ignore
import type { BatchDelete202Response } from '../models';
// @ts-ignore
import type { BatchDelete207Response } from '../models';
// @ts-ignore
import type { BatchDeleteRequestInner } from '../models';
// @ts-ignore
import type { BatchMove200Response } from '../models';
// @ts-ignore
import type { BatchMove202Response } from '../models';
// @ts-ignore
import type { BatchMove207Response } from '../models';
// @ts-ignore
import type { BatchMoveRequestInner } from '../models';
/**
 * BatchApi - axios parameter creator
 */
export const BatchApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 用于批量复制目录或文件
         * @summary 批量复制目录或文件
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {BatchCopyCopyEnum} copy 开启批量复制操作
         * @param {string} accessToken 访问令牌，必选参数
         * @param {Array<BatchCopyRequestInner>} batchCopyRequest 
         * @param {string} [userId] 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        batchCopy: async (libraryId: string, spaceId: string, copy: BatchCopyCopyEnum, accessToken: string, batchCopyRequest: Array<BatchCopyRequestInner>, userId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'libraryId' is not null or undefined
            assertParamExists('batchCopy', 'libraryId', libraryId)
            // verify required parameter 'spaceId' is not null or undefined
            assertParamExists('batchCopy', 'spaceId', spaceId)
            // verify required parameter 'copy' is not null or undefined
            assertParamExists('batchCopy', 'copy', copy)
            // verify required parameter 'accessToken' is not null or undefined
            assertParamExists('batchCopy', 'accessToken', accessToken)
            // verify required parameter 'batchCopyRequest' is not null or undefined
            assertParamExists('batchCopy', 'batchCopyRequest', batchCopyRequest)
            const localVarPath = `/api/v1/batch/{LibraryId}/{SpaceId}`
                .replace(`{${"LibraryId"}}`, encodeURIComponent(String(libraryId)))
                .replace(`{${"SpaceId"}}`, encodeURIComponent(String(spaceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (copy !== undefined) {
                localVarQueryParameter['copy'] = copy;
            }

            if (accessToken !== undefined) {
                localVarQueryParameter['access_token'] = accessToken;
            }

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(batchCopyRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 用于批量删除目录或文件
         * @summary 批量删除目录或文件
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {BatchDeleteDeleteEnum} _delete 开启批量删除操作
         * @param {string} accessToken 访问令牌，必选参数
         * @param {Array<BatchDeleteRequestInner>} batchDeleteRequest 
         * @param {string} [userId] 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        batchDelete: async (libraryId: string, spaceId: string, _delete: BatchDeleteDeleteEnum, accessToken: string, batchDeleteRequest: Array<BatchDeleteRequestInner>, userId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'libraryId' is not null or undefined
            assertParamExists('batchDelete', 'libraryId', libraryId)
            // verify required parameter 'spaceId' is not null or undefined
            assertParamExists('batchDelete', 'spaceId', spaceId)
            // verify required parameter '_delete' is not null or undefined
            assertParamExists('batchDelete', '_delete', _delete)
            // verify required parameter 'accessToken' is not null or undefined
            assertParamExists('batchDelete', 'accessToken', accessToken)
            // verify required parameter 'batchDeleteRequest' is not null or undefined
            assertParamExists('batchDelete', 'batchDeleteRequest', batchDeleteRequest)
            const localVarPath = `/api/v1/batch/{LibraryId}/{SpaceId}#2`
                .replace(`{${"LibraryId"}}`, encodeURIComponent(String(libraryId)))
                .replace(`{${"SpaceId"}}`, encodeURIComponent(String(spaceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (_delete !== undefined) {
                localVarQueryParameter['delete'] = _delete;
            }

            if (accessToken !== undefined) {
                localVarQueryParameter['access_token'] = accessToken;
            }

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(batchDeleteRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 用于批量重命名或移动目录或文件
         * @summary 批量重命名或移动目录或文件
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {BatchMoveMoveEnum} move 开启批量重命名或移动操作
         * @param {string} accessToken 访问令牌，必选参数
         * @param {Array<BatchMoveRequestInner>} batchMoveRequest 
         * @param {string} [userId] 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        batchMove: async (libraryId: string, spaceId: string, move: BatchMoveMoveEnum, accessToken: string, batchMoveRequest: Array<BatchMoveRequestInner>, userId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'libraryId' is not null or undefined
            assertParamExists('batchMove', 'libraryId', libraryId)
            // verify required parameter 'spaceId' is not null or undefined
            assertParamExists('batchMove', 'spaceId', spaceId)
            // verify required parameter 'move' is not null or undefined
            assertParamExists('batchMove', 'move', move)
            // verify required parameter 'accessToken' is not null or undefined
            assertParamExists('batchMove', 'accessToken', accessToken)
            // verify required parameter 'batchMoveRequest' is not null or undefined
            assertParamExists('batchMove', 'batchMoveRequest', batchMoveRequest)
            const localVarPath = `/api/v1/batch/{LibraryId}/{SpaceId}#1`
                .replace(`{${"LibraryId"}}`, encodeURIComponent(String(libraryId)))
                .replace(`{${"SpaceId"}}`, encodeURIComponent(String(spaceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (move !== undefined) {
                localVarQueryParameter['move'] = move;
            }

            if (accessToken !== undefined) {
                localVarQueryParameter['access_token'] = accessToken;
            }

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(batchMoveRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BatchApi - functional programming interface
 */
export const BatchApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BatchApiAxiosParamCreator(configuration)
    return {
        /**
         * 用于批量复制目录或文件
         * @summary 批量复制目录或文件
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {BatchCopyCopyEnum} copy 开启批量复制操作
         * @param {string} accessToken 访问令牌，必选参数
         * @param {Array<BatchCopyRequestInner>} batchCopyRequest 
         * @param {string} [userId] 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async batchCopy(libraryId: string, spaceId: string, copy: BatchCopyCopyEnum, accessToken: string, batchCopyRequest: Array<BatchCopyRequestInner>, userId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BatchCopy200Response | BatchCopy202Response | BatchCopy207Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.batchCopy(libraryId, spaceId, copy, accessToken, batchCopyRequest, userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BatchApi.batchCopy']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 用于批量删除目录或文件
         * @summary 批量删除目录或文件
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {BatchDeleteDeleteEnum} _delete 开启批量删除操作
         * @param {string} accessToken 访问令牌，必选参数
         * @param {Array<BatchDeleteRequestInner>} batchDeleteRequest 
         * @param {string} [userId] 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async batchDelete(libraryId: string, spaceId: string, _delete: BatchDeleteDeleteEnum, accessToken: string, batchDeleteRequest: Array<BatchDeleteRequestInner>, userId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BatchDelete200Response | BatchDelete202Response | BatchDelete207Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.batchDelete(libraryId, spaceId, _delete, accessToken, batchDeleteRequest, userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BatchApi.batchDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 用于批量重命名或移动目录或文件
         * @summary 批量重命名或移动目录或文件
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {BatchMoveMoveEnum} move 开启批量重命名或移动操作
         * @param {string} accessToken 访问令牌，必选参数
         * @param {Array<BatchMoveRequestInner>} batchMoveRequest 
         * @param {string} [userId] 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async batchMove(libraryId: string, spaceId: string, move: BatchMoveMoveEnum, accessToken: string, batchMoveRequest: Array<BatchMoveRequestInner>, userId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BatchMove200Response | BatchMove202Response | BatchMove207Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.batchMove(libraryId, spaceId, move, accessToken, batchMoveRequest, userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BatchApi.batchMove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BatchApi - factory interface
 */
export const BatchApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BatchApiFp(configuration)
    return {
        /**
         * 用于批量复制目录或文件
         * @summary 批量复制目录或文件
         * @param {BatchApiBatchCopyRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        batchCopy(requestParameters: BatchApiBatchCopyRequest, options?: RawAxiosRequestConfig): AxiosPromise<BatchCopy200Response | BatchCopy202Response | BatchCopy207Response> {
            return localVarFp.batchCopy(requestParameters.libraryId, requestParameters.spaceId, requestParameters.copy, requestParameters.accessToken, requestParameters.batchCopyRequest, requestParameters.userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 用于批量删除目录或文件
         * @summary 批量删除目录或文件
         * @param {BatchApiBatchDeleteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        batchDelete(requestParameters: BatchApiBatchDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<BatchDelete200Response | BatchDelete202Response | BatchDelete207Response> {
            return localVarFp.batchDelete(requestParameters.libraryId, requestParameters.spaceId, requestParameters._delete, requestParameters.accessToken, requestParameters.batchDeleteRequest, requestParameters.userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 用于批量重命名或移动目录或文件
         * @summary 批量重命名或移动目录或文件
         * @param {BatchApiBatchMoveRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        batchMove(requestParameters: BatchApiBatchMoveRequest, options?: RawAxiosRequestConfig): AxiosPromise<BatchMove200Response | BatchMove202Response | BatchMove207Response> {
            return localVarFp.batchMove(requestParameters.libraryId, requestParameters.spaceId, requestParameters.move, requestParameters.accessToken, requestParameters.batchMoveRequest, requestParameters.userId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for batchCopy operation in BatchApi.
 */
export interface BatchApiBatchCopyRequest {
    /**
     * 媒体库 ID，必选参数
     */
    readonly libraryId: string

    /**
     * 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
     */
    readonly spaceId: string

    /**
     * 开启批量复制操作
     */
    readonly copy: BatchCopyCopyEnum

    /**
     * 访问令牌，必选参数
     */
    readonly accessToken: string

    readonly batchCopyRequest: Array<BatchCopyRequestInner>

    /**
     * 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
     */
    readonly userId?: string
}

/**
 * Request parameters for batchDelete operation in BatchApi.
 */
export interface BatchApiBatchDeleteRequest {
    /**
     * 媒体库 ID，必选参数
     */
    readonly libraryId: string

    /**
     * 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
     */
    readonly spaceId: string

    /**
     * 开启批量删除操作
     */
    readonly _delete: BatchDeleteDeleteEnum

    /**
     * 访问令牌，必选参数
     */
    readonly accessToken: string

    readonly batchDeleteRequest: Array<BatchDeleteRequestInner>

    /**
     * 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
     */
    readonly userId?: string
}

/**
 * Request parameters for batchMove operation in BatchApi.
 */
export interface BatchApiBatchMoveRequest {
    /**
     * 媒体库 ID，必选参数
     */
    readonly libraryId: string

    /**
     * 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
     */
    readonly spaceId: string

    /**
     * 开启批量重命名或移动操作
     */
    readonly move: BatchMoveMoveEnum

    /**
     * 访问令牌，必选参数
     */
    readonly accessToken: string

    readonly batchMoveRequest: Array<BatchMoveRequestInner>

    /**
     * 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
     */
    readonly userId?: string
}

/**
 * BatchApi - object-oriented interface
 */
export class BatchApi extends BaseAPI {
    /**
     * 用于批量复制目录或文件
     * @summary 批量复制目录或文件
     * @param {BatchApiBatchCopyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public batchCopy(requestParameters: BatchApiBatchCopyRequest, options?: RawAxiosRequestConfig) {
        return BatchApiFp(this.configuration).batchCopy(requestParameters.libraryId, requestParameters.spaceId, requestParameters.copy, requestParameters.accessToken, requestParameters.batchCopyRequest, requestParameters.userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 用于批量删除目录或文件
     * @summary 批量删除目录或文件
     * @param {BatchApiBatchDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public batchDelete(requestParameters: BatchApiBatchDeleteRequest, options?: RawAxiosRequestConfig) {
        return BatchApiFp(this.configuration).batchDelete(requestParameters.libraryId, requestParameters.spaceId, requestParameters._delete, requestParameters.accessToken, requestParameters.batchDeleteRequest, requestParameters.userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 用于批量重命名或移动目录或文件
     * @summary 批量重命名或移动目录或文件
     * @param {BatchApiBatchMoveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public batchMove(requestParameters: BatchApiBatchMoveRequest, options?: RawAxiosRequestConfig) {
        return BatchApiFp(this.configuration).batchMove(requestParameters.libraryId, requestParameters.spaceId, requestParameters.move, requestParameters.accessToken, requestParameters.batchMoveRequest, requestParameters.userId, options).then((request) => request(this.axios, this.basePath));
    }
}

export const BatchCopyCopyEnum = {
    NUMBER_1: 1
} as const;
export type BatchCopyCopyEnum = typeof BatchCopyCopyEnum[keyof typeof BatchCopyCopyEnum];
export const BatchDeleteDeleteEnum = {
    NUMBER_1: 1
} as const;
export type BatchDeleteDeleteEnum = typeof BatchDeleteDeleteEnum[keyof typeof BatchDeleteDeleteEnum];
export const BatchMoveMoveEnum = {
    NUMBER_1: 1
} as const;
export type BatchMoveMoveEnum = typeof BatchMoveMoveEnum[keyof typeof BatchMoveMoveEnum];
