/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CopyDirectory200Response } from '../models';
// @ts-ignore
import type { CopyDirectory202Response } from '../models';
// @ts-ignore
import type { CopyDirectoryRequest } from '../models';
// @ts-ignore
import type { CreateDirectory201Response } from '../models';
// @ts-ignore
import type { DeleteFile200Response } from '../models';
// @ts-ignore
import type { InfoFileOrDirectory200Response } from '../models';
// @ts-ignore
import type { ListDirectory200Response } from '../models';
// @ts-ignore
import type { ListDirectoryByPage200Response } from '../models';
// @ts-ignore
import type { MoveDirectoryRequest } from '../models';
// @ts-ignore
import type { UpdateDirectoryLabelsRequest } from '../models';
// @ts-ignore
import type { UpdateFileLabelsRequest } from '../models';
/**
 * DirectoryApi - axios parameter creator
 */
export const DirectoryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 用于检查目录或相簿状态
         * @summary 检查目录或相簿状态
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {string} filePath 文件路径｜目录路径，对于多级文件路径，使用斜杠(/)分隔，例如 foo/bar/file.txt；对于根目录，该参数留空
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {string} [userId] 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkDirectoryStatus: async (libraryId: string, spaceId: string, filePath: string, accessToken?: string, librarySecret?: string, userId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'libraryId' is not null or undefined
            assertParamExists('checkDirectoryStatus', 'libraryId', libraryId)
            // verify required parameter 'spaceId' is not null or undefined
            assertParamExists('checkDirectoryStatus', 'spaceId', spaceId)
            // verify required parameter 'filePath' is not null or undefined
            assertParamExists('checkDirectoryStatus', 'filePath', filePath)
            const localVarPath = `/api/v1/directory/{LibraryId}/{SpaceId}/{FilePath}`
                .replace(`{${"LibraryId"}}`, encodeURIComponent(String(libraryId)))
                .replace(`{${"SpaceId"}}`, encodeURIComponent(String(spaceId)))
                .replace(`{${"FilePath"}}`, encodeURIComponent(String(filePath)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'HEAD', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (accessToken !== undefined) {
                localVarQueryParameter['access_token'] = accessToken;
            }

            if (librarySecret !== undefined) {
                localVarQueryParameter['library_secret'] = librarySecret;
            }

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 用于复制目录或相簿。 - 自动创建中间所需的各级父目录。 
         * @summary 复制目录或相簿
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {string} filePath 文件路径｜目录路径，对于多级文件路径，使用斜杠(/)分隔，例如 foo/bar/file.txt；对于根目录，该参数留空
         * @param {CopyDirectoryRequest} copyDirectoryRequest 
         * @param {CopyDirectoryConflictResolutionStrategyEnum} [conflictResolutionStrategy] 最后一级目录冲突时的处理方式，ask冲突时返回 HTTP 409，rename冲突时自动重命名最后一级目录，默认为 ask
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {string} [userId] 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        copyDirectory: async (libraryId: string, spaceId: string, filePath: string, copyDirectoryRequest: CopyDirectoryRequest, conflictResolutionStrategy?: CopyDirectoryConflictResolutionStrategyEnum, accessToken?: string, librarySecret?: string, userId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'libraryId' is not null or undefined
            assertParamExists('copyDirectory', 'libraryId', libraryId)
            // verify required parameter 'spaceId' is not null or undefined
            assertParamExists('copyDirectory', 'spaceId', spaceId)
            // verify required parameter 'filePath' is not null or undefined
            assertParamExists('copyDirectory', 'filePath', filePath)
            // verify required parameter 'copyDirectoryRequest' is not null or undefined
            assertParamExists('copyDirectory', 'copyDirectoryRequest', copyDirectoryRequest)
            const localVarPath = `/api/v1/directory/{LibraryId}/{SpaceId}/{FilePath}#1`
                .replace(`{${"LibraryId"}}`, encodeURIComponent(String(libraryId)))
                .replace(`{${"SpaceId"}}`, encodeURIComponent(String(spaceId)))
                .replace(`{${"FilePath"}}`, encodeURIComponent(String(filePath)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (conflictResolutionStrategy !== undefined) {
                localVarQueryParameter['conflict_resolution_strategy'] = conflictResolutionStrategy;
            }

            if (accessToken !== undefined) {
                localVarQueryParameter['access_token'] = accessToken;
            }

            if (librarySecret !== undefined) {
                localVarQueryParameter['library_secret'] = librarySecret;
            }

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(copyDirectoryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 用于创建目录或相簿。 - 媒体类型媒体库可以进一步设置是否为分相簿媒体库，当设置为不分相簿时，则不允许创建目录或相簿，当设置为分相簿时，仅允许创建1层目录或相簿；文件类型媒体库不限制目录层数； - 自动创建中间所需的各级父目录； - 即使 ConflictResolutionStrategy 为 rename，如果路径中的某一父级实际为文件，则依然会返回 HTTP 409 Conflict 及 SameNameDirectoryOrFileExists 错误码。 
         * @summary 创建目录或相簿
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {string} filePath 文件路径｜目录路径，对于多级文件路径，使用斜杠(/)分隔，例如 foo/bar/file.txt；对于根目录，该参数留空
         * @param {CreateDirectoryConflictResolutionStrategyEnum} [conflictResolutionStrategy] 最后一级目录冲突时的处理方式，ask冲突时返回 HTTP 409，rename冲突时自动重命名最后一级目录，默认为 ask
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {string} [userId] 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
         * @param {CreateDirectoryWithInodeEnum} [withInode] 是否返回 inode，即文件目录 ID，0 或 1，默认不返回
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDirectory: async (libraryId: string, spaceId: string, filePath: string, conflictResolutionStrategy?: CreateDirectoryConflictResolutionStrategyEnum, accessToken?: string, librarySecret?: string, userId?: string, withInode?: CreateDirectoryWithInodeEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'libraryId' is not null or undefined
            assertParamExists('createDirectory', 'libraryId', libraryId)
            // verify required parameter 'spaceId' is not null or undefined
            assertParamExists('createDirectory', 'spaceId', spaceId)
            // verify required parameter 'filePath' is not null or undefined
            assertParamExists('createDirectory', 'filePath', filePath)
            const localVarPath = `/api/v1/directory/{LibraryId}/{SpaceId}/{FilePath}`
                .replace(`{${"LibraryId"}}`, encodeURIComponent(String(libraryId)))
                .replace(`{${"SpaceId"}}`, encodeURIComponent(String(spaceId)))
                .replace(`{${"FilePath"}}`, encodeURIComponent(String(filePath)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (conflictResolutionStrategy !== undefined) {
                localVarQueryParameter['conflict_resolution_strategy'] = conflictResolutionStrategy;
            }

            if (accessToken !== undefined) {
                localVarQueryParameter['access_token'] = accessToken;
            }

            if (librarySecret !== undefined) {
                localVarQueryParameter['library_secret'] = librarySecret;
            }

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }

            if (withInode !== undefined) {
                localVarQueryParameter['with_inode'] = withInode;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 用于删除目录或相簿。如果媒体库启用回收站功能，则该接口不会永久删除目录或相簿，而是将目录或相簿以及其下的文件移入回收站，可通过相关接口永久删除或恢复回收站内的目录或相簿，或直接清空回收站；
         * @summary 删除目录或相簿
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {string} filePath 文件路径｜目录路径，对于多级文件路径，使用斜杠(/)分隔，例如 foo/bar/file.txt；对于根目录，该参数留空
         * @param {DeleteDirectoryPermanentEnum} [permanent] 当媒体库开启回收站时，则该参数指定将文件移入回收站还是永久删除文件，1: 永久删除，0: 移入回收站，默认为 0
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {string} [userId] 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDirectory: async (libraryId: string, spaceId: string, filePath: string, permanent?: DeleteDirectoryPermanentEnum, accessToken?: string, librarySecret?: string, userId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'libraryId' is not null or undefined
            assertParamExists('deleteDirectory', 'libraryId', libraryId)
            // verify required parameter 'spaceId' is not null or undefined
            assertParamExists('deleteDirectory', 'spaceId', spaceId)
            // verify required parameter 'filePath' is not null or undefined
            assertParamExists('deleteDirectory', 'filePath', filePath)
            const localVarPath = `/api/v1/directory/{LibraryId}/{SpaceId}/{FilePath}`
                .replace(`{${"LibraryId"}}`, encodeURIComponent(String(libraryId)))
                .replace(`{${"SpaceId"}}`, encodeURIComponent(String(spaceId)))
                .replace(`{${"FilePath"}}`, encodeURIComponent(String(filePath)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (permanent !== undefined) {
                localVarQueryParameter['permanent'] = permanent;
            }

            if (accessToken !== undefined) {
                localVarQueryParameter['access_token'] = accessToken;
            }

            if (librarySecret !== undefined) {
                localVarQueryParameter['library_secret'] = librarySecret;
            }

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 此接口可同时用于查看文件或文件夹详情，路径如果为文件，则返回文件详情，如果为文件夹，则返回文件夹详情。 
         * @summary 查看文件、目录或相簿详情
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {string} filePath 文件路径｜目录路径，对于多级文件路径，使用斜杠(/)分隔，例如 foo/bar/file.txt；对于根目录，该参数留空
         * @param {InfoFileOrDirectoryInfoEnum} info 固定为 1
         * @param {InfoFileOrDirectoryWithInodeEnum} [withInode] 是否返回 inode，即文件目录 ID，0 或 1，默认不返回
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {InfoFileOrDirectoryWithFavoriteStatusEnum} [withFavoriteStatus] 是否返回收藏状态，0 或 1，默认不返回
         * @param {InfoFileOrDirectoryWithContentCasEnum} [withContentCas] 0 或 1，是否返回文件内容的Cas标识，可选，默认不返回
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        infoFileOrDirectory: async (libraryId: string, spaceId: string, filePath: string, info: InfoFileOrDirectoryInfoEnum, withInode?: InfoFileOrDirectoryWithInodeEnum, accessToken?: string, librarySecret?: string, withFavoriteStatus?: InfoFileOrDirectoryWithFavoriteStatusEnum, withContentCas?: InfoFileOrDirectoryWithContentCasEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'libraryId' is not null or undefined
            assertParamExists('infoFileOrDirectory', 'libraryId', libraryId)
            // verify required parameter 'spaceId' is not null or undefined
            assertParamExists('infoFileOrDirectory', 'spaceId', spaceId)
            // verify required parameter 'filePath' is not null or undefined
            assertParamExists('infoFileOrDirectory', 'filePath', filePath)
            // verify required parameter 'info' is not null or undefined
            assertParamExists('infoFileOrDirectory', 'info', info)
            const localVarPath = `/api/v1/directory/{LibraryId}/{SpaceId}/{FilePath}#1`
                .replace(`{${"LibraryId"}}`, encodeURIComponent(String(libraryId)))
                .replace(`{${"SpaceId"}}`, encodeURIComponent(String(spaceId)))
                .replace(`{${"FilePath"}}`, encodeURIComponent(String(filePath)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (info !== undefined) {
                localVarQueryParameter['info'] = info;
            }

            if (withInode !== undefined) {
                localVarQueryParameter['with_inode'] = withInode;
            }

            if (accessToken !== undefined) {
                localVarQueryParameter['access_token'] = accessToken;
            }

            if (librarySecret !== undefined) {
                localVarQueryParameter['library_secret'] = librarySecret;
            }

            if (withFavoriteStatus !== undefined) {
                localVarQueryParameter['with_favorite_status'] = withFavoriteStatus;
            }

            if (withContentCas !== undefined) {
                localVarQueryParameter['with_content_cas'] = withContentCas;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 用于列出目录或相簿内容。 目录内容的列出顺序为：首先按照字典序列出子目录，随后根据上传时间列出媒体库中的媒体资源，或根据文件名列出文件库中的文件资源。 
         * @summary 列出目录或相簿内容
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {string} filePath 文件路径｜目录路径，对于多级文件路径，使用斜杠(/)分隔，例如 foo/bar/file.txt；对于根目录，该参数留空
         * @param {ListDirectoryByMarkerEnum} byMarker 固定传 1，表示使用 marker 方式分页
         * @param {string} [marker] 用于顺序列出分页的标识
         * @param {number} [limit] 用于顺序列出分页时本地列出的项目数限制，不传默认值20，最大返回100
         * @param {ListDirectoryOrderByEnum} [orderBy] 排序字段
         * @param {ListDirectoryOrderByTypeEnum} [orderByType] 排序方式，升序为 asc，降序为 desc
         * @param {ListDirectoryFilterEnum} [filter] 筛选方式，不传返回全部，onlyDir 只返回文件夹，onlyFile 只返回文件
         * @param {ListDirectorySortTypeEnum} [sortType] 排序方式，不传则文件和文件夹单独排序，先返回文件夹，后返回文件。union 文件和文件夹拉通排序
         * @param {ListDirectoryWithInodeEnum} [withInode] 是否返回 inode，即文件目录 ID，0 或 1，默认不返回
         * @param {ListDirectoryWithFavoriteStatusEnum} [withFavoriteStatus] 是否返回收藏状态，0 或 1，默认不返回
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {string} [userId] 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
         * @param {ListDirectoryWithContentCasEnum} [withContentCas] 0 或 1，是否返回文件内容的Cas标识，可选，默认不返回
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDirectory: async (libraryId: string, spaceId: string, filePath: string, byMarker: ListDirectoryByMarkerEnum, marker?: string, limit?: number, orderBy?: ListDirectoryOrderByEnum, orderByType?: ListDirectoryOrderByTypeEnum, filter?: ListDirectoryFilterEnum, sortType?: ListDirectorySortTypeEnum, withInode?: ListDirectoryWithInodeEnum, withFavoriteStatus?: ListDirectoryWithFavoriteStatusEnum, accessToken?: string, librarySecret?: string, userId?: string, withContentCas?: ListDirectoryWithContentCasEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'libraryId' is not null or undefined
            assertParamExists('listDirectory', 'libraryId', libraryId)
            // verify required parameter 'spaceId' is not null or undefined
            assertParamExists('listDirectory', 'spaceId', spaceId)
            // verify required parameter 'filePath' is not null or undefined
            assertParamExists('listDirectory', 'filePath', filePath)
            // verify required parameter 'byMarker' is not null or undefined
            assertParamExists('listDirectory', 'byMarker', byMarker)
            const localVarPath = `/api/v1/directory/{LibraryId}/{SpaceId}/{FilePath}`
                .replace(`{${"LibraryId"}}`, encodeURIComponent(String(libraryId)))
                .replace(`{${"SpaceId"}}`, encodeURIComponent(String(spaceId)))
                .replace(`{${"FilePath"}}`, encodeURIComponent(String(filePath)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (byMarker !== undefined) {
                localVarQueryParameter['by-marker'] = byMarker;
            }

            if (marker !== undefined) {
                localVarQueryParameter['marker'] = marker;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (orderBy !== undefined) {
                localVarQueryParameter['order_by'] = orderBy;
            }

            if (orderByType !== undefined) {
                localVarQueryParameter['order_by_type'] = orderByType;
            }

            if (filter !== undefined) {
                localVarQueryParameter['filter'] = filter;
            }

            if (sortType !== undefined) {
                localVarQueryParameter['sort_type'] = sortType;
            }

            if (withInode !== undefined) {
                localVarQueryParameter['with_inode'] = withInode;
            }

            if (withFavoriteStatus !== undefined) {
                localVarQueryParameter['with_favorite_status'] = withFavoriteStatus;
            }

            if (accessToken !== undefined) {
                localVarQueryParameter['access_token'] = accessToken;
            }

            if (librarySecret !== undefined) {
                localVarQueryParameter['library_secret'] = librarySecret;
            }

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }

            if (withContentCas !== undefined) {
                localVarQueryParameter['with_content_cas'] = withContentCas;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 用于列出目录或相簿内容。 目录内容的列出顺序为：首先按照字典序列出子目录，随后根据上传时间列出媒体库中的媒体资源，或根据文件名列出文件库中的文件资源。 page翻页的深度会有限制，强烈建议业务方改用marker翻页的形式。 
         * @summary 列出目录或相簿内容（传统分页）
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {string} filePath 文件路径｜目录路径，对于多级文件路径，使用斜杠(/)分隔，例如 foo/bar/file.txt；对于根目录，该参数留空
         * @param {ListDirectoryByPageByPageEnum} byPage 固定传 1，表示使用 page 方式分页
         * @param {number} [page] 分页码，默认第一页，最大翻页的条目数（Page*PageSize的大小）是1万
         * @param {number} [pageSize] 分页大小，默认 20，最大翻页的条目数（Page*PageSize的大小）是1万
         * @param {ListDirectoryByPageOrderByEnum} [orderBy] 排序字段
         * @param {ListDirectoryByPageOrderByTypeEnum} [orderByType] 排序方式，升序为 asc，降序为 desc
         * @param {ListDirectoryByPageFilterEnum} [filter] 筛选方式，不传返回全部，onlyDir 只返回文件夹，onlyFile 只返回文件
         * @param {ListDirectoryByPageSortTypeEnum} [sortType] 排序方式，不传则文件和文件夹单独排序，先返回文件夹，后返回文件。union 文件和文件夹拉通排序
         * @param {ListDirectoryByPageWithInodeEnum} [withInode] 是否返回 inode，即文件目录 ID，0 或 1，默认不返回
         * @param {ListDirectoryByPageWithFavoriteStatusEnum} [withFavoriteStatus] 是否返回收藏状态，0 或 1，默认不返回
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {string} [userId] 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
         * @param {ListDirectoryByPageWithContentCasEnum} [withContentCas] 0 或 1，是否返回文件内容的Cas标识，可选，默认不返回
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDirectoryByPage: async (libraryId: string, spaceId: string, filePath: string, byPage: ListDirectoryByPageByPageEnum, page?: number, pageSize?: number, orderBy?: ListDirectoryByPageOrderByEnum, orderByType?: ListDirectoryByPageOrderByTypeEnum, filter?: ListDirectoryByPageFilterEnum, sortType?: ListDirectoryByPageSortTypeEnum, withInode?: ListDirectoryByPageWithInodeEnum, withFavoriteStatus?: ListDirectoryByPageWithFavoriteStatusEnum, accessToken?: string, librarySecret?: string, userId?: string, withContentCas?: ListDirectoryByPageWithContentCasEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'libraryId' is not null or undefined
            assertParamExists('listDirectoryByPage', 'libraryId', libraryId)
            // verify required parameter 'spaceId' is not null or undefined
            assertParamExists('listDirectoryByPage', 'spaceId', spaceId)
            // verify required parameter 'filePath' is not null or undefined
            assertParamExists('listDirectoryByPage', 'filePath', filePath)
            // verify required parameter 'byPage' is not null or undefined
            assertParamExists('listDirectoryByPage', 'byPage', byPage)
            const localVarPath = `/api/v1/directory/{LibraryId}/{SpaceId}/{FilePath}#2`
                .replace(`{${"LibraryId"}}`, encodeURIComponent(String(libraryId)))
                .replace(`{${"SpaceId"}}`, encodeURIComponent(String(spaceId)))
                .replace(`{${"FilePath"}}`, encodeURIComponent(String(filePath)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (byPage !== undefined) {
                localVarQueryParameter['by-page'] = byPage;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['page_size'] = pageSize;
            }

            if (orderBy !== undefined) {
                localVarQueryParameter['order_by'] = orderBy;
            }

            if (orderByType !== undefined) {
                localVarQueryParameter['order_by_type'] = orderByType;
            }

            if (filter !== undefined) {
                localVarQueryParameter['filter'] = filter;
            }

            if (sortType !== undefined) {
                localVarQueryParameter['sort_type'] = sortType;
            }

            if (withInode !== undefined) {
                localVarQueryParameter['with_inode'] = withInode;
            }

            if (withFavoriteStatus !== undefined) {
                localVarQueryParameter['with_favorite_status'] = withFavoriteStatus;
            }

            if (accessToken !== undefined) {
                localVarQueryParameter['access_token'] = accessToken;
            }

            if (librarySecret !== undefined) {
                localVarQueryParameter['library_secret'] = librarySecret;
            }

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }

            if (withContentCas !== undefined) {
                localVarQueryParameter['with_content_cas'] = withContentCas;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 用于重命名或移动目录或相簿。 要求权限： admin、space_admin 或 move_directory。 该接口的源和目标均需要指定完整的目录路径或相簿名；对于文件类型媒体库，源与目标可以跨越多层级多目录，来实现将目录移动到任意其他父目录下的功能，且支持同时修改目录名； 自动创建中间所需的各级父目录。 
         * @summary 重命名或移动目录或相簿
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {string} filePath 文件路径｜目录路径，对于多级文件路径，使用斜杠(/)分隔，例如 foo/bar/file.txt；对于根目录，该参数留空
         * @param {MoveDirectoryRequest} moveDirectoryRequest 
         * @param {MoveDirectoryConflictResolutionStrategyEnum} [conflictResolutionStrategy] 最后一级目录冲突时的处理方式，ask冲突时返回 HTTP 409，rename冲突时自动重命名最后一级目录，默认为 ask
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {string} [userId] 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        moveDirectory: async (libraryId: string, spaceId: string, filePath: string, moveDirectoryRequest: MoveDirectoryRequest, conflictResolutionStrategy?: MoveDirectoryConflictResolutionStrategyEnum, accessToken?: string, librarySecret?: string, userId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'libraryId' is not null or undefined
            assertParamExists('moveDirectory', 'libraryId', libraryId)
            // verify required parameter 'spaceId' is not null or undefined
            assertParamExists('moveDirectory', 'spaceId', spaceId)
            // verify required parameter 'filePath' is not null or undefined
            assertParamExists('moveDirectory', 'filePath', filePath)
            // verify required parameter 'moveDirectoryRequest' is not null or undefined
            assertParamExists('moveDirectory', 'moveDirectoryRequest', moveDirectoryRequest)
            const localVarPath = `/api/v1/directory/{LibraryId}/{SpaceId}/{FilePath}#2`
                .replace(`{${"LibraryId"}}`, encodeURIComponent(String(libraryId)))
                .replace(`{${"SpaceId"}}`, encodeURIComponent(String(spaceId)))
                .replace(`{${"FilePath"}}`, encodeURIComponent(String(filePath)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (conflictResolutionStrategy !== undefined) {
                localVarQueryParameter['conflict_resolution_strategy'] = conflictResolutionStrategy;
            }

            if (accessToken !== undefined) {
                localVarQueryParameter['access_token'] = accessToken;
            }

            if (librarySecret !== undefined) {
                localVarQueryParameter['library_secret'] = librarySecret;
            }

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(moveDirectoryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 用于更新目录自定义标签。需要 admin 权限或 spaceAdmin 权限
         * @summary 更新目录自定义标签
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {string} filePath 文件路径｜目录路径，对于多级文件路径，使用斜杠(/)分隔，例如 foo/bar/file.txt；对于根目录，该参数留空
         * @param {UpdateDirectoryLabelsUpdateEnum} update 固定为 1
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {UpdateDirectoryLabelsRequest} [updateDirectoryLabelsRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateDirectoryLabels: async (libraryId: string, spaceId: string, filePath: string, update: UpdateDirectoryLabelsUpdateEnum, accessToken?: string, librarySecret?: string, updateDirectoryLabelsRequest?: UpdateDirectoryLabelsRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'libraryId' is not null or undefined
            assertParamExists('updateDirectoryLabels', 'libraryId', libraryId)
            // verify required parameter 'spaceId' is not null or undefined
            assertParamExists('updateDirectoryLabels', 'spaceId', spaceId)
            // verify required parameter 'filePath' is not null or undefined
            assertParamExists('updateDirectoryLabels', 'filePath', filePath)
            // verify required parameter 'update' is not null or undefined
            assertParamExists('updateDirectoryLabels', 'update', update)
            const localVarPath = `/api/v1/directory/{LibraryId}/{SpaceId}/{FilePath}`
                .replace(`{${"LibraryId"}}`, encodeURIComponent(String(libraryId)))
                .replace(`{${"SpaceId"}}`, encodeURIComponent(String(spaceId)))
                .replace(`{${"FilePath"}}`, encodeURIComponent(String(filePath)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (update !== undefined) {
                localVarQueryParameter['update'] = update;
            }

            if (accessToken !== undefined) {
                localVarQueryParameter['access_token'] = accessToken;
            }

            if (librarySecret !== undefined) {
                localVarQueryParameter['library_secret'] = librarySecret;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateDirectoryLabelsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 用于更新文件的标签（Labels）或分类（Category）。 需要 admin 权限或 spaceAdmin 权限。 
         * @summary 更新文件标签或分类
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {string} filePath 文件路径｜目录路径，对于多级文件路径，使用斜杠(/)分隔，例如 foo/bar/file.txt；对于根目录，该参数留空
         * @param {UpdateFileLabelsUpdateEnum} update 固定为 1
         * @param {UpdateFileLabelsRequest} updateFileLabelsRequest 
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateFileLabels: async (libraryId: string, spaceId: string, filePath: string, update: UpdateFileLabelsUpdateEnum, updateFileLabelsRequest: UpdateFileLabelsRequest, accessToken?: string, librarySecret?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'libraryId' is not null or undefined
            assertParamExists('updateFileLabels', 'libraryId', libraryId)
            // verify required parameter 'spaceId' is not null or undefined
            assertParamExists('updateFileLabels', 'spaceId', spaceId)
            // verify required parameter 'filePath' is not null or undefined
            assertParamExists('updateFileLabels', 'filePath', filePath)
            // verify required parameter 'update' is not null or undefined
            assertParamExists('updateFileLabels', 'update', update)
            // verify required parameter 'updateFileLabelsRequest' is not null or undefined
            assertParamExists('updateFileLabels', 'updateFileLabelsRequest', updateFileLabelsRequest)
            const localVarPath = `/api/v1/directory/{LibraryId}/{SpaceId}/{FilePath}#1`
                .replace(`{${"LibraryId"}}`, encodeURIComponent(String(libraryId)))
                .replace(`{${"SpaceId"}}`, encodeURIComponent(String(spaceId)))
                .replace(`{${"FilePath"}}`, encodeURIComponent(String(filePath)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (update !== undefined) {
                localVarQueryParameter['update'] = update;
            }

            if (accessToken !== undefined) {
                localVarQueryParameter['access_token'] = accessToken;
            }

            if (librarySecret !== undefined) {
                localVarQueryParameter['library_secret'] = librarySecret;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateFileLabelsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DirectoryApi - functional programming interface
 */
export const DirectoryApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DirectoryApiAxiosParamCreator(configuration)
    return {
        /**
         * 用于检查目录或相簿状态
         * @summary 检查目录或相簿状态
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {string} filePath 文件路径｜目录路径，对于多级文件路径，使用斜杠(/)分隔，例如 foo/bar/file.txt；对于根目录，该参数留空
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {string} [userId] 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async checkDirectoryStatus(libraryId: string, spaceId: string, filePath: string, accessToken?: string, librarySecret?: string, userId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.checkDirectoryStatus(libraryId, spaceId, filePath, accessToken, librarySecret, userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DirectoryApi.checkDirectoryStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 用于复制目录或相簿。 - 自动创建中间所需的各级父目录。 
         * @summary 复制目录或相簿
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {string} filePath 文件路径｜目录路径，对于多级文件路径，使用斜杠(/)分隔，例如 foo/bar/file.txt；对于根目录，该参数留空
         * @param {CopyDirectoryRequest} copyDirectoryRequest 
         * @param {CopyDirectoryConflictResolutionStrategyEnum} [conflictResolutionStrategy] 最后一级目录冲突时的处理方式，ask冲突时返回 HTTP 409，rename冲突时自动重命名最后一级目录，默认为 ask
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {string} [userId] 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async copyDirectory(libraryId: string, spaceId: string, filePath: string, copyDirectoryRequest: CopyDirectoryRequest, conflictResolutionStrategy?: CopyDirectoryConflictResolutionStrategyEnum, accessToken?: string, librarySecret?: string, userId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CopyDirectory202Response | void | CopyDirectory200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.copyDirectory(libraryId, spaceId, filePath, copyDirectoryRequest, conflictResolutionStrategy, accessToken, librarySecret, userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DirectoryApi.copyDirectory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 用于创建目录或相簿。 - 媒体类型媒体库可以进一步设置是否为分相簿媒体库，当设置为不分相簿时，则不允许创建目录或相簿，当设置为分相簿时，仅允许创建1层目录或相簿；文件类型媒体库不限制目录层数； - 自动创建中间所需的各级父目录； - 即使 ConflictResolutionStrategy 为 rename，如果路径中的某一父级实际为文件，则依然会返回 HTTP 409 Conflict 及 SameNameDirectoryOrFileExists 错误码。 
         * @summary 创建目录或相簿
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {string} filePath 文件路径｜目录路径，对于多级文件路径，使用斜杠(/)分隔，例如 foo/bar/file.txt；对于根目录，该参数留空
         * @param {CreateDirectoryConflictResolutionStrategyEnum} [conflictResolutionStrategy] 最后一级目录冲突时的处理方式，ask冲突时返回 HTTP 409，rename冲突时自动重命名最后一级目录，默认为 ask
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {string} [userId] 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
         * @param {CreateDirectoryWithInodeEnum} [withInode] 是否返回 inode，即文件目录 ID，0 或 1，默认不返回
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createDirectory(libraryId: string, spaceId: string, filePath: string, conflictResolutionStrategy?: CreateDirectoryConflictResolutionStrategyEnum, accessToken?: string, librarySecret?: string, userId?: string, withInode?: CreateDirectoryWithInodeEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDirectory201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createDirectory(libraryId, spaceId, filePath, conflictResolutionStrategy, accessToken, librarySecret, userId, withInode, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DirectoryApi.createDirectory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 用于删除目录或相簿。如果媒体库启用回收站功能，则该接口不会永久删除目录或相簿，而是将目录或相簿以及其下的文件移入回收站，可通过相关接口永久删除或恢复回收站内的目录或相簿，或直接清空回收站；
         * @summary 删除目录或相簿
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {string} filePath 文件路径｜目录路径，对于多级文件路径，使用斜杠(/)分隔，例如 foo/bar/file.txt；对于根目录，该参数留空
         * @param {DeleteDirectoryPermanentEnum} [permanent] 当媒体库开启回收站时，则该参数指定将文件移入回收站还是永久删除文件，1: 永久删除，0: 移入回收站，默认为 0
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {string} [userId] 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteDirectory(libraryId: string, spaceId: string, filePath: string, permanent?: DeleteDirectoryPermanentEnum, accessToken?: string, librarySecret?: string, userId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void | DeleteFile200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteDirectory(libraryId, spaceId, filePath, permanent, accessToken, librarySecret, userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DirectoryApi.deleteDirectory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 此接口可同时用于查看文件或文件夹详情，路径如果为文件，则返回文件详情，如果为文件夹，则返回文件夹详情。 
         * @summary 查看文件、目录或相簿详情
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {string} filePath 文件路径｜目录路径，对于多级文件路径，使用斜杠(/)分隔，例如 foo/bar/file.txt；对于根目录，该参数留空
         * @param {InfoFileOrDirectoryInfoEnum} info 固定为 1
         * @param {InfoFileOrDirectoryWithInodeEnum} [withInode] 是否返回 inode，即文件目录 ID，0 或 1，默认不返回
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {InfoFileOrDirectoryWithFavoriteStatusEnum} [withFavoriteStatus] 是否返回收藏状态，0 或 1，默认不返回
         * @param {InfoFileOrDirectoryWithContentCasEnum} [withContentCas] 0 或 1，是否返回文件内容的Cas标识，可选，默认不返回
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async infoFileOrDirectory(libraryId: string, spaceId: string, filePath: string, info: InfoFileOrDirectoryInfoEnum, withInode?: InfoFileOrDirectoryWithInodeEnum, accessToken?: string, librarySecret?: string, withFavoriteStatus?: InfoFileOrDirectoryWithFavoriteStatusEnum, withContentCas?: InfoFileOrDirectoryWithContentCasEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InfoFileOrDirectory200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.infoFileOrDirectory(libraryId, spaceId, filePath, info, withInode, accessToken, librarySecret, withFavoriteStatus, withContentCas, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DirectoryApi.infoFileOrDirectory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 用于列出目录或相簿内容。 目录内容的列出顺序为：首先按照字典序列出子目录，随后根据上传时间列出媒体库中的媒体资源，或根据文件名列出文件库中的文件资源。 
         * @summary 列出目录或相簿内容
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {string} filePath 文件路径｜目录路径，对于多级文件路径，使用斜杠(/)分隔，例如 foo/bar/file.txt；对于根目录，该参数留空
         * @param {ListDirectoryByMarkerEnum} byMarker 固定传 1，表示使用 marker 方式分页
         * @param {string} [marker] 用于顺序列出分页的标识
         * @param {number} [limit] 用于顺序列出分页时本地列出的项目数限制，不传默认值20，最大返回100
         * @param {ListDirectoryOrderByEnum} [orderBy] 排序字段
         * @param {ListDirectoryOrderByTypeEnum} [orderByType] 排序方式，升序为 asc，降序为 desc
         * @param {ListDirectoryFilterEnum} [filter] 筛选方式，不传返回全部，onlyDir 只返回文件夹，onlyFile 只返回文件
         * @param {ListDirectorySortTypeEnum} [sortType] 排序方式，不传则文件和文件夹单独排序，先返回文件夹，后返回文件。union 文件和文件夹拉通排序
         * @param {ListDirectoryWithInodeEnum} [withInode] 是否返回 inode，即文件目录 ID，0 或 1，默认不返回
         * @param {ListDirectoryWithFavoriteStatusEnum} [withFavoriteStatus] 是否返回收藏状态，0 或 1，默认不返回
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {string} [userId] 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
         * @param {ListDirectoryWithContentCasEnum} [withContentCas] 0 或 1，是否返回文件内容的Cas标识，可选，默认不返回
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listDirectory(libraryId: string, spaceId: string, filePath: string, byMarker: ListDirectoryByMarkerEnum, marker?: string, limit?: number, orderBy?: ListDirectoryOrderByEnum, orderByType?: ListDirectoryOrderByTypeEnum, filter?: ListDirectoryFilterEnum, sortType?: ListDirectorySortTypeEnum, withInode?: ListDirectoryWithInodeEnum, withFavoriteStatus?: ListDirectoryWithFavoriteStatusEnum, accessToken?: string, librarySecret?: string, userId?: string, withContentCas?: ListDirectoryWithContentCasEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListDirectory200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listDirectory(libraryId, spaceId, filePath, byMarker, marker, limit, orderBy, orderByType, filter, sortType, withInode, withFavoriteStatus, accessToken, librarySecret, userId, withContentCas, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DirectoryApi.listDirectory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 用于列出目录或相簿内容。 目录内容的列出顺序为：首先按照字典序列出子目录，随后根据上传时间列出媒体库中的媒体资源，或根据文件名列出文件库中的文件资源。 page翻页的深度会有限制，强烈建议业务方改用marker翻页的形式。 
         * @summary 列出目录或相簿内容（传统分页）
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {string} filePath 文件路径｜目录路径，对于多级文件路径，使用斜杠(/)分隔，例如 foo/bar/file.txt；对于根目录，该参数留空
         * @param {ListDirectoryByPageByPageEnum} byPage 固定传 1，表示使用 page 方式分页
         * @param {number} [page] 分页码，默认第一页，最大翻页的条目数（Page*PageSize的大小）是1万
         * @param {number} [pageSize] 分页大小，默认 20，最大翻页的条目数（Page*PageSize的大小）是1万
         * @param {ListDirectoryByPageOrderByEnum} [orderBy] 排序字段
         * @param {ListDirectoryByPageOrderByTypeEnum} [orderByType] 排序方式，升序为 asc，降序为 desc
         * @param {ListDirectoryByPageFilterEnum} [filter] 筛选方式，不传返回全部，onlyDir 只返回文件夹，onlyFile 只返回文件
         * @param {ListDirectoryByPageSortTypeEnum} [sortType] 排序方式，不传则文件和文件夹单独排序，先返回文件夹，后返回文件。union 文件和文件夹拉通排序
         * @param {ListDirectoryByPageWithInodeEnum} [withInode] 是否返回 inode，即文件目录 ID，0 或 1，默认不返回
         * @param {ListDirectoryByPageWithFavoriteStatusEnum} [withFavoriteStatus] 是否返回收藏状态，0 或 1，默认不返回
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {string} [userId] 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
         * @param {ListDirectoryByPageWithContentCasEnum} [withContentCas] 0 或 1，是否返回文件内容的Cas标识，可选，默认不返回
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listDirectoryByPage(libraryId: string, spaceId: string, filePath: string, byPage: ListDirectoryByPageByPageEnum, page?: number, pageSize?: number, orderBy?: ListDirectoryByPageOrderByEnum, orderByType?: ListDirectoryByPageOrderByTypeEnum, filter?: ListDirectoryByPageFilterEnum, sortType?: ListDirectoryByPageSortTypeEnum, withInode?: ListDirectoryByPageWithInodeEnum, withFavoriteStatus?: ListDirectoryByPageWithFavoriteStatusEnum, accessToken?: string, librarySecret?: string, userId?: string, withContentCas?: ListDirectoryByPageWithContentCasEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListDirectoryByPage200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listDirectoryByPage(libraryId, spaceId, filePath, byPage, page, pageSize, orderBy, orderByType, filter, sortType, withInode, withFavoriteStatus, accessToken, librarySecret, userId, withContentCas, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DirectoryApi.listDirectoryByPage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 用于重命名或移动目录或相簿。 要求权限： admin、space_admin 或 move_directory。 该接口的源和目标均需要指定完整的目录路径或相簿名；对于文件类型媒体库，源与目标可以跨越多层级多目录，来实现将目录移动到任意其他父目录下的功能，且支持同时修改目录名； 自动创建中间所需的各级父目录。 
         * @summary 重命名或移动目录或相簿
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {string} filePath 文件路径｜目录路径，对于多级文件路径，使用斜杠(/)分隔，例如 foo/bar/file.txt；对于根目录，该参数留空
         * @param {MoveDirectoryRequest} moveDirectoryRequest 
         * @param {MoveDirectoryConflictResolutionStrategyEnum} [conflictResolutionStrategy] 最后一级目录冲突时的处理方式，ask冲突时返回 HTTP 409，rename冲突时自动重命名最后一级目录，默认为 ask
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {string} [userId] 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async moveDirectory(libraryId: string, spaceId: string, filePath: string, moveDirectoryRequest: MoveDirectoryRequest, conflictResolutionStrategy?: MoveDirectoryConflictResolutionStrategyEnum, accessToken?: string, librarySecret?: string, userId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void | CopyDirectory200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.moveDirectory(libraryId, spaceId, filePath, moveDirectoryRequest, conflictResolutionStrategy, accessToken, librarySecret, userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DirectoryApi.moveDirectory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 用于更新目录自定义标签。需要 admin 权限或 spaceAdmin 权限
         * @summary 更新目录自定义标签
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {string} filePath 文件路径｜目录路径，对于多级文件路径，使用斜杠(/)分隔，例如 foo/bar/file.txt；对于根目录，该参数留空
         * @param {UpdateDirectoryLabelsUpdateEnum} update 固定为 1
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {UpdateDirectoryLabelsRequest} [updateDirectoryLabelsRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateDirectoryLabels(libraryId: string, spaceId: string, filePath: string, update: UpdateDirectoryLabelsUpdateEnum, accessToken?: string, librarySecret?: string, updateDirectoryLabelsRequest?: UpdateDirectoryLabelsRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateDirectoryLabels(libraryId, spaceId, filePath, update, accessToken, librarySecret, updateDirectoryLabelsRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DirectoryApi.updateDirectoryLabels']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 用于更新文件的标签（Labels）或分类（Category）。 需要 admin 权限或 spaceAdmin 权限。 
         * @summary 更新文件标签或分类
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {string} filePath 文件路径｜目录路径，对于多级文件路径，使用斜杠(/)分隔，例如 foo/bar/file.txt；对于根目录，该参数留空
         * @param {UpdateFileLabelsUpdateEnum} update 固定为 1
         * @param {UpdateFileLabelsRequest} updateFileLabelsRequest 
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateFileLabels(libraryId: string, spaceId: string, filePath: string, update: UpdateFileLabelsUpdateEnum, updateFileLabelsRequest: UpdateFileLabelsRequest, accessToken?: string, librarySecret?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateFileLabels(libraryId, spaceId, filePath, update, updateFileLabelsRequest, accessToken, librarySecret, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DirectoryApi.updateFileLabels']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DirectoryApi - factory interface
 */
export const DirectoryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DirectoryApiFp(configuration)
    return {
        /**
         * 用于检查目录或相簿状态
         * @summary 检查目录或相簿状态
         * @param {DirectoryApiCheckDirectoryStatusRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkDirectoryStatus(requestParameters: DirectoryApiCheckDirectoryStatusRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.checkDirectoryStatus(requestParameters.libraryId, requestParameters.spaceId, requestParameters.filePath, requestParameters.accessToken, requestParameters.librarySecret, requestParameters.userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 用于复制目录或相簿。 - 自动创建中间所需的各级父目录。 
         * @summary 复制目录或相簿
         * @param {DirectoryApiCopyDirectoryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        copyDirectory(requestParameters: DirectoryApiCopyDirectoryRequest, options?: RawAxiosRequestConfig): AxiosPromise<CopyDirectory202Response | void | CopyDirectory200Response> {
            return localVarFp.copyDirectory(requestParameters.libraryId, requestParameters.spaceId, requestParameters.filePath, requestParameters.copyDirectoryRequest, requestParameters.conflictResolutionStrategy, requestParameters.accessToken, requestParameters.librarySecret, requestParameters.userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 用于创建目录或相簿。 - 媒体类型媒体库可以进一步设置是否为分相簿媒体库，当设置为不分相簿时，则不允许创建目录或相簿，当设置为分相簿时，仅允许创建1层目录或相簿；文件类型媒体库不限制目录层数； - 自动创建中间所需的各级父目录； - 即使 ConflictResolutionStrategy 为 rename，如果路径中的某一父级实际为文件，则依然会返回 HTTP 409 Conflict 及 SameNameDirectoryOrFileExists 错误码。 
         * @summary 创建目录或相簿
         * @param {DirectoryApiCreateDirectoryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDirectory(requestParameters: DirectoryApiCreateDirectoryRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDirectory201Response> {
            return localVarFp.createDirectory(requestParameters.libraryId, requestParameters.spaceId, requestParameters.filePath, requestParameters.conflictResolutionStrategy, requestParameters.accessToken, requestParameters.librarySecret, requestParameters.userId, requestParameters.withInode, options).then((request) => request(axios, basePath));
        },
        /**
         * 用于删除目录或相簿。如果媒体库启用回收站功能，则该接口不会永久删除目录或相簿，而是将目录或相簿以及其下的文件移入回收站，可通过相关接口永久删除或恢复回收站内的目录或相簿，或直接清空回收站；
         * @summary 删除目录或相簿
         * @param {DirectoryApiDeleteDirectoryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDirectory(requestParameters: DirectoryApiDeleteDirectoryRequest, options?: RawAxiosRequestConfig): AxiosPromise<void | DeleteFile200Response> {
            return localVarFp.deleteDirectory(requestParameters.libraryId, requestParameters.spaceId, requestParameters.filePath, requestParameters.permanent, requestParameters.accessToken, requestParameters.librarySecret, requestParameters.userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 此接口可同时用于查看文件或文件夹详情，路径如果为文件，则返回文件详情，如果为文件夹，则返回文件夹详情。 
         * @summary 查看文件、目录或相簿详情
         * @param {DirectoryApiInfoFileOrDirectoryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        infoFileOrDirectory(requestParameters: DirectoryApiInfoFileOrDirectoryRequest, options?: RawAxiosRequestConfig): AxiosPromise<InfoFileOrDirectory200Response> {
            return localVarFp.infoFileOrDirectory(requestParameters.libraryId, requestParameters.spaceId, requestParameters.filePath, requestParameters.info, requestParameters.withInode, requestParameters.accessToken, requestParameters.librarySecret, requestParameters.withFavoriteStatus, requestParameters.withContentCas, options).then((request) => request(axios, basePath));
        },
        /**
         * 用于列出目录或相簿内容。 目录内容的列出顺序为：首先按照字典序列出子目录，随后根据上传时间列出媒体库中的媒体资源，或根据文件名列出文件库中的文件资源。 
         * @summary 列出目录或相簿内容
         * @param {DirectoryApiListDirectoryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDirectory(requestParameters: DirectoryApiListDirectoryRequest, options?: RawAxiosRequestConfig): AxiosPromise<ListDirectory200Response> {
            return localVarFp.listDirectory(requestParameters.libraryId, requestParameters.spaceId, requestParameters.filePath, requestParameters.byMarker, requestParameters.marker, requestParameters.limit, requestParameters.orderBy, requestParameters.orderByType, requestParameters.filter, requestParameters.sortType, requestParameters.withInode, requestParameters.withFavoriteStatus, requestParameters.accessToken, requestParameters.librarySecret, requestParameters.userId, requestParameters.withContentCas, options).then((request) => request(axios, basePath));
        },
        /**
         * 用于列出目录或相簿内容。 目录内容的列出顺序为：首先按照字典序列出子目录，随后根据上传时间列出媒体库中的媒体资源，或根据文件名列出文件库中的文件资源。 page翻页的深度会有限制，强烈建议业务方改用marker翻页的形式。 
         * @summary 列出目录或相簿内容（传统分页）
         * @param {DirectoryApiListDirectoryByPageRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDirectoryByPage(requestParameters: DirectoryApiListDirectoryByPageRequest, options?: RawAxiosRequestConfig): AxiosPromise<ListDirectoryByPage200Response> {
            return localVarFp.listDirectoryByPage(requestParameters.libraryId, requestParameters.spaceId, requestParameters.filePath, requestParameters.byPage, requestParameters.page, requestParameters.pageSize, requestParameters.orderBy, requestParameters.orderByType, requestParameters.filter, requestParameters.sortType, requestParameters.withInode, requestParameters.withFavoriteStatus, requestParameters.accessToken, requestParameters.librarySecret, requestParameters.userId, requestParameters.withContentCas, options).then((request) => request(axios, basePath));
        },
        /**
         * 用于重命名或移动目录或相簿。 要求权限： admin、space_admin 或 move_directory。 该接口的源和目标均需要指定完整的目录路径或相簿名；对于文件类型媒体库，源与目标可以跨越多层级多目录，来实现将目录移动到任意其他父目录下的功能，且支持同时修改目录名； 自动创建中间所需的各级父目录。 
         * @summary 重命名或移动目录或相簿
         * @param {DirectoryApiMoveDirectoryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        moveDirectory(requestParameters: DirectoryApiMoveDirectoryRequest, options?: RawAxiosRequestConfig): AxiosPromise<void | CopyDirectory200Response> {
            return localVarFp.moveDirectory(requestParameters.libraryId, requestParameters.spaceId, requestParameters.filePath, requestParameters.moveDirectoryRequest, requestParameters.conflictResolutionStrategy, requestParameters.accessToken, requestParameters.librarySecret, requestParameters.userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 用于更新目录自定义标签。需要 admin 权限或 spaceAdmin 权限
         * @summary 更新目录自定义标签
         * @param {DirectoryApiUpdateDirectoryLabelsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateDirectoryLabels(requestParameters: DirectoryApiUpdateDirectoryLabelsRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.updateDirectoryLabels(requestParameters.libraryId, requestParameters.spaceId, requestParameters.filePath, requestParameters.update, requestParameters.accessToken, requestParameters.librarySecret, requestParameters.updateDirectoryLabelsRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 用于更新文件的标签（Labels）或分类（Category）。 需要 admin 权限或 spaceAdmin 权限。 
         * @summary 更新文件标签或分类
         * @param {DirectoryApiUpdateFileLabelsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateFileLabels(requestParameters: DirectoryApiUpdateFileLabelsRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.updateFileLabels(requestParameters.libraryId, requestParameters.spaceId, requestParameters.filePath, requestParameters.update, requestParameters.updateFileLabelsRequest, requestParameters.accessToken, requestParameters.librarySecret, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for checkDirectoryStatus operation in DirectoryApi.
 */
export interface DirectoryApiCheckDirectoryStatusRequest {
    /**
     * 媒体库 ID，必选参数
     */
    readonly libraryId: string

    /**
     * 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
     */
    readonly spaceId: string

    /**
     * 文件路径｜目录路径，对于多级文件路径，使用斜杠(/)分隔，例如 foo/bar/file.txt；对于根目录，该参数留空
     */
    readonly filePath: string

    /**
     * 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
     */
    readonly accessToken?: string

    /**
     * 访问媒体库密钥，可选参数
     */
    readonly librarySecret?: string

    /**
     * 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
     */
    readonly userId?: string
}

/**
 * Request parameters for copyDirectory operation in DirectoryApi.
 */
export interface DirectoryApiCopyDirectoryRequest {
    /**
     * 媒体库 ID，必选参数
     */
    readonly libraryId: string

    /**
     * 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
     */
    readonly spaceId: string

    /**
     * 文件路径｜目录路径，对于多级文件路径，使用斜杠(/)分隔，例如 foo/bar/file.txt；对于根目录，该参数留空
     */
    readonly filePath: string

    readonly copyDirectoryRequest: CopyDirectoryRequest

    /**
     * 最后一级目录冲突时的处理方式，ask冲突时返回 HTTP 409，rename冲突时自动重命名最后一级目录，默认为 ask
     */
    readonly conflictResolutionStrategy?: CopyDirectoryConflictResolutionStrategyEnum

    /**
     * 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
     */
    readonly accessToken?: string

    /**
     * 访问媒体库密钥，可选参数
     */
    readonly librarySecret?: string

    /**
     * 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
     */
    readonly userId?: string
}

/**
 * Request parameters for createDirectory operation in DirectoryApi.
 */
export interface DirectoryApiCreateDirectoryRequest {
    /**
     * 媒体库 ID，必选参数
     */
    readonly libraryId: string

    /**
     * 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
     */
    readonly spaceId: string

    /**
     * 文件路径｜目录路径，对于多级文件路径，使用斜杠(/)分隔，例如 foo/bar/file.txt；对于根目录，该参数留空
     */
    readonly filePath: string

    /**
     * 最后一级目录冲突时的处理方式，ask冲突时返回 HTTP 409，rename冲突时自动重命名最后一级目录，默认为 ask
     */
    readonly conflictResolutionStrategy?: CreateDirectoryConflictResolutionStrategyEnum

    /**
     * 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
     */
    readonly accessToken?: string

    /**
     * 访问媒体库密钥，可选参数
     */
    readonly librarySecret?: string

    /**
     * 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
     */
    readonly userId?: string

    /**
     * 是否返回 inode，即文件目录 ID，0 或 1，默认不返回
     */
    readonly withInode?: CreateDirectoryWithInodeEnum
}

/**
 * Request parameters for deleteDirectory operation in DirectoryApi.
 */
export interface DirectoryApiDeleteDirectoryRequest {
    /**
     * 媒体库 ID，必选参数
     */
    readonly libraryId: string

    /**
     * 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
     */
    readonly spaceId: string

    /**
     * 文件路径｜目录路径，对于多级文件路径，使用斜杠(/)分隔，例如 foo/bar/file.txt；对于根目录，该参数留空
     */
    readonly filePath: string

    /**
     * 当媒体库开启回收站时，则该参数指定将文件移入回收站还是永久删除文件，1: 永久删除，0: 移入回收站，默认为 0
     */
    readonly permanent?: DeleteDirectoryPermanentEnum

    /**
     * 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
     */
    readonly accessToken?: string

    /**
     * 访问媒体库密钥，可选参数
     */
    readonly librarySecret?: string

    /**
     * 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
     */
    readonly userId?: string
}

/**
 * Request parameters for infoFileOrDirectory operation in DirectoryApi.
 */
export interface DirectoryApiInfoFileOrDirectoryRequest {
    /**
     * 媒体库 ID，必选参数
     */
    readonly libraryId: string

    /**
     * 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
     */
    readonly spaceId: string

    /**
     * 文件路径｜目录路径，对于多级文件路径，使用斜杠(/)分隔，例如 foo/bar/file.txt；对于根目录，该参数留空
     */
    readonly filePath: string

    /**
     * 固定为 1
     */
    readonly info: InfoFileOrDirectoryInfoEnum

    /**
     * 是否返回 inode，即文件目录 ID，0 或 1，默认不返回
     */
    readonly withInode?: InfoFileOrDirectoryWithInodeEnum

    /**
     * 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
     */
    readonly accessToken?: string

    /**
     * 访问媒体库密钥，可选参数
     */
    readonly librarySecret?: string

    /**
     * 是否返回收藏状态，0 或 1，默认不返回
     */
    readonly withFavoriteStatus?: InfoFileOrDirectoryWithFavoriteStatusEnum

    /**
     * 0 或 1，是否返回文件内容的Cas标识，可选，默认不返回
     */
    readonly withContentCas?: InfoFileOrDirectoryWithContentCasEnum
}

/**
 * Request parameters for listDirectory operation in DirectoryApi.
 */
export interface DirectoryApiListDirectoryRequest {
    /**
     * 媒体库 ID，必选参数
     */
    readonly libraryId: string

    /**
     * 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
     */
    readonly spaceId: string

    /**
     * 文件路径｜目录路径，对于多级文件路径，使用斜杠(/)分隔，例如 foo/bar/file.txt；对于根目录，该参数留空
     */
    readonly filePath: string

    /**
     * 固定传 1，表示使用 marker 方式分页
     */
    readonly byMarker: ListDirectoryByMarkerEnum

    /**
     * 用于顺序列出分页的标识
     */
    readonly marker?: string

    /**
     * 用于顺序列出分页时本地列出的项目数限制，不传默认值20，最大返回100
     */
    readonly limit?: number

    /**
     * 排序字段
     */
    readonly orderBy?: ListDirectoryOrderByEnum

    /**
     * 排序方式，升序为 asc，降序为 desc
     */
    readonly orderByType?: ListDirectoryOrderByTypeEnum

    /**
     * 筛选方式，不传返回全部，onlyDir 只返回文件夹，onlyFile 只返回文件
     */
    readonly filter?: ListDirectoryFilterEnum

    /**
     * 排序方式，不传则文件和文件夹单独排序，先返回文件夹，后返回文件。union 文件和文件夹拉通排序
     */
    readonly sortType?: ListDirectorySortTypeEnum

    /**
     * 是否返回 inode，即文件目录 ID，0 或 1，默认不返回
     */
    readonly withInode?: ListDirectoryWithInodeEnum

    /**
     * 是否返回收藏状态，0 或 1，默认不返回
     */
    readonly withFavoriteStatus?: ListDirectoryWithFavoriteStatusEnum

    /**
     * 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
     */
    readonly accessToken?: string

    /**
     * 访问媒体库密钥，可选参数
     */
    readonly librarySecret?: string

    /**
     * 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
     */
    readonly userId?: string

    /**
     * 0 或 1，是否返回文件内容的Cas标识，可选，默认不返回
     */
    readonly withContentCas?: ListDirectoryWithContentCasEnum
}

/**
 * Request parameters for listDirectoryByPage operation in DirectoryApi.
 */
export interface DirectoryApiListDirectoryByPageRequest {
    /**
     * 媒体库 ID，必选参数
     */
    readonly libraryId: string

    /**
     * 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
     */
    readonly spaceId: string

    /**
     * 文件路径｜目录路径，对于多级文件路径，使用斜杠(/)分隔，例如 foo/bar/file.txt；对于根目录，该参数留空
     */
    readonly filePath: string

    /**
     * 固定传 1，表示使用 page 方式分页
     */
    readonly byPage: ListDirectoryByPageByPageEnum

    /**
     * 分页码，默认第一页，最大翻页的条目数（Page*PageSize的大小）是1万
     */
    readonly page?: number

    /**
     * 分页大小，默认 20，最大翻页的条目数（Page*PageSize的大小）是1万
     */
    readonly pageSize?: number

    /**
     * 排序字段
     */
    readonly orderBy?: ListDirectoryByPageOrderByEnum

    /**
     * 排序方式，升序为 asc，降序为 desc
     */
    readonly orderByType?: ListDirectoryByPageOrderByTypeEnum

    /**
     * 筛选方式，不传返回全部，onlyDir 只返回文件夹，onlyFile 只返回文件
     */
    readonly filter?: ListDirectoryByPageFilterEnum

    /**
     * 排序方式，不传则文件和文件夹单独排序，先返回文件夹，后返回文件。union 文件和文件夹拉通排序
     */
    readonly sortType?: ListDirectoryByPageSortTypeEnum

    /**
     * 是否返回 inode，即文件目录 ID，0 或 1，默认不返回
     */
    readonly withInode?: ListDirectoryByPageWithInodeEnum

    /**
     * 是否返回收藏状态，0 或 1，默认不返回
     */
    readonly withFavoriteStatus?: ListDirectoryByPageWithFavoriteStatusEnum

    /**
     * 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
     */
    readonly accessToken?: string

    /**
     * 访问媒体库密钥，可选参数
     */
    readonly librarySecret?: string

    /**
     * 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
     */
    readonly userId?: string

    /**
     * 0 或 1，是否返回文件内容的Cas标识，可选，默认不返回
     */
    readonly withContentCas?: ListDirectoryByPageWithContentCasEnum
}

/**
 * Request parameters for moveDirectory operation in DirectoryApi.
 */
export interface DirectoryApiMoveDirectoryRequest {
    /**
     * 媒体库 ID，必选参数
     */
    readonly libraryId: string

    /**
     * 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
     */
    readonly spaceId: string

    /**
     * 文件路径｜目录路径，对于多级文件路径，使用斜杠(/)分隔，例如 foo/bar/file.txt；对于根目录，该参数留空
     */
    readonly filePath: string

    readonly moveDirectoryRequest: MoveDirectoryRequest

    /**
     * 最后一级目录冲突时的处理方式，ask冲突时返回 HTTP 409，rename冲突时自动重命名最后一级目录，默认为 ask
     */
    readonly conflictResolutionStrategy?: MoveDirectoryConflictResolutionStrategyEnum

    /**
     * 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
     */
    readonly accessToken?: string

    /**
     * 访问媒体库密钥，可选参数
     */
    readonly librarySecret?: string

    /**
     * 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
     */
    readonly userId?: string
}

/**
 * Request parameters for updateDirectoryLabels operation in DirectoryApi.
 */
export interface DirectoryApiUpdateDirectoryLabelsRequest {
    /**
     * 媒体库 ID，必选参数
     */
    readonly libraryId: string

    /**
     * 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
     */
    readonly spaceId: string

    /**
     * 文件路径｜目录路径，对于多级文件路径，使用斜杠(/)分隔，例如 foo/bar/file.txt；对于根目录，该参数留空
     */
    readonly filePath: string

    /**
     * 固定为 1
     */
    readonly update: UpdateDirectoryLabelsUpdateEnum

    /**
     * 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
     */
    readonly accessToken?: string

    /**
     * 访问媒体库密钥，可选参数
     */
    readonly librarySecret?: string

    readonly updateDirectoryLabelsRequest?: UpdateDirectoryLabelsRequest
}

/**
 * Request parameters for updateFileLabels operation in DirectoryApi.
 */
export interface DirectoryApiUpdateFileLabelsRequest {
    /**
     * 媒体库 ID，必选参数
     */
    readonly libraryId: string

    /**
     * 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
     */
    readonly spaceId: string

    /**
     * 文件路径｜目录路径，对于多级文件路径，使用斜杠(/)分隔，例如 foo/bar/file.txt；对于根目录，该参数留空
     */
    readonly filePath: string

    /**
     * 固定为 1
     */
    readonly update: UpdateFileLabelsUpdateEnum

    readonly updateFileLabelsRequest: UpdateFileLabelsRequest

    /**
     * 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
     */
    readonly accessToken?: string

    /**
     * 访问媒体库密钥，可选参数
     */
    readonly librarySecret?: string
}

/**
 * DirectoryApi - object-oriented interface
 */
export class DirectoryApi extends BaseAPI {
    /**
     * 用于检查目录或相簿状态
     * @summary 检查目录或相簿状态
     * @param {DirectoryApiCheckDirectoryStatusRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public checkDirectoryStatus(requestParameters: DirectoryApiCheckDirectoryStatusRequest, options?: RawAxiosRequestConfig) {
        return DirectoryApiFp(this.configuration).checkDirectoryStatus(requestParameters.libraryId, requestParameters.spaceId, requestParameters.filePath, requestParameters.accessToken, requestParameters.librarySecret, requestParameters.userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 用于复制目录或相簿。 - 自动创建中间所需的各级父目录。 
     * @summary 复制目录或相簿
     * @param {DirectoryApiCopyDirectoryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public copyDirectory(requestParameters: DirectoryApiCopyDirectoryRequest, options?: RawAxiosRequestConfig) {
        return DirectoryApiFp(this.configuration).copyDirectory(requestParameters.libraryId, requestParameters.spaceId, requestParameters.filePath, requestParameters.copyDirectoryRequest, requestParameters.conflictResolutionStrategy, requestParameters.accessToken, requestParameters.librarySecret, requestParameters.userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 用于创建目录或相簿。 - 媒体类型媒体库可以进一步设置是否为分相簿媒体库，当设置为不分相簿时，则不允许创建目录或相簿，当设置为分相簿时，仅允许创建1层目录或相簿；文件类型媒体库不限制目录层数； - 自动创建中间所需的各级父目录； - 即使 ConflictResolutionStrategy 为 rename，如果路径中的某一父级实际为文件，则依然会返回 HTTP 409 Conflict 及 SameNameDirectoryOrFileExists 错误码。 
     * @summary 创建目录或相簿
     * @param {DirectoryApiCreateDirectoryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createDirectory(requestParameters: DirectoryApiCreateDirectoryRequest, options?: RawAxiosRequestConfig) {
        return DirectoryApiFp(this.configuration).createDirectory(requestParameters.libraryId, requestParameters.spaceId, requestParameters.filePath, requestParameters.conflictResolutionStrategy, requestParameters.accessToken, requestParameters.librarySecret, requestParameters.userId, requestParameters.withInode, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 用于删除目录或相簿。如果媒体库启用回收站功能，则该接口不会永久删除目录或相簿，而是将目录或相簿以及其下的文件移入回收站，可通过相关接口永久删除或恢复回收站内的目录或相簿，或直接清空回收站；
     * @summary 删除目录或相簿
     * @param {DirectoryApiDeleteDirectoryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteDirectory(requestParameters: DirectoryApiDeleteDirectoryRequest, options?: RawAxiosRequestConfig) {
        return DirectoryApiFp(this.configuration).deleteDirectory(requestParameters.libraryId, requestParameters.spaceId, requestParameters.filePath, requestParameters.permanent, requestParameters.accessToken, requestParameters.librarySecret, requestParameters.userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 此接口可同时用于查看文件或文件夹详情，路径如果为文件，则返回文件详情，如果为文件夹，则返回文件夹详情。 
     * @summary 查看文件、目录或相簿详情
     * @param {DirectoryApiInfoFileOrDirectoryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public infoFileOrDirectory(requestParameters: DirectoryApiInfoFileOrDirectoryRequest, options?: RawAxiosRequestConfig) {
        return DirectoryApiFp(this.configuration).infoFileOrDirectory(requestParameters.libraryId, requestParameters.spaceId, requestParameters.filePath, requestParameters.info, requestParameters.withInode, requestParameters.accessToken, requestParameters.librarySecret, requestParameters.withFavoriteStatus, requestParameters.withContentCas, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 用于列出目录或相簿内容。 目录内容的列出顺序为：首先按照字典序列出子目录，随后根据上传时间列出媒体库中的媒体资源，或根据文件名列出文件库中的文件资源。 
     * @summary 列出目录或相簿内容
     * @param {DirectoryApiListDirectoryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listDirectory(requestParameters: DirectoryApiListDirectoryRequest, options?: RawAxiosRequestConfig) {
        return DirectoryApiFp(this.configuration).listDirectory(requestParameters.libraryId, requestParameters.spaceId, requestParameters.filePath, requestParameters.byMarker, requestParameters.marker, requestParameters.limit, requestParameters.orderBy, requestParameters.orderByType, requestParameters.filter, requestParameters.sortType, requestParameters.withInode, requestParameters.withFavoriteStatus, requestParameters.accessToken, requestParameters.librarySecret, requestParameters.userId, requestParameters.withContentCas, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 用于列出目录或相簿内容。 目录内容的列出顺序为：首先按照字典序列出子目录，随后根据上传时间列出媒体库中的媒体资源，或根据文件名列出文件库中的文件资源。 page翻页的深度会有限制，强烈建议业务方改用marker翻页的形式。 
     * @summary 列出目录或相簿内容（传统分页）
     * @param {DirectoryApiListDirectoryByPageRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listDirectoryByPage(requestParameters: DirectoryApiListDirectoryByPageRequest, options?: RawAxiosRequestConfig) {
        return DirectoryApiFp(this.configuration).listDirectoryByPage(requestParameters.libraryId, requestParameters.spaceId, requestParameters.filePath, requestParameters.byPage, requestParameters.page, requestParameters.pageSize, requestParameters.orderBy, requestParameters.orderByType, requestParameters.filter, requestParameters.sortType, requestParameters.withInode, requestParameters.withFavoriteStatus, requestParameters.accessToken, requestParameters.librarySecret, requestParameters.userId, requestParameters.withContentCas, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 用于重命名或移动目录或相簿。 要求权限： admin、space_admin 或 move_directory。 该接口的源和目标均需要指定完整的目录路径或相簿名；对于文件类型媒体库，源与目标可以跨越多层级多目录，来实现将目录移动到任意其他父目录下的功能，且支持同时修改目录名； 自动创建中间所需的各级父目录。 
     * @summary 重命名或移动目录或相簿
     * @param {DirectoryApiMoveDirectoryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public moveDirectory(requestParameters: DirectoryApiMoveDirectoryRequest, options?: RawAxiosRequestConfig) {
        return DirectoryApiFp(this.configuration).moveDirectory(requestParameters.libraryId, requestParameters.spaceId, requestParameters.filePath, requestParameters.moveDirectoryRequest, requestParameters.conflictResolutionStrategy, requestParameters.accessToken, requestParameters.librarySecret, requestParameters.userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 用于更新目录自定义标签。需要 admin 权限或 spaceAdmin 权限
     * @summary 更新目录自定义标签
     * @param {DirectoryApiUpdateDirectoryLabelsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateDirectoryLabels(requestParameters: DirectoryApiUpdateDirectoryLabelsRequest, options?: RawAxiosRequestConfig) {
        return DirectoryApiFp(this.configuration).updateDirectoryLabels(requestParameters.libraryId, requestParameters.spaceId, requestParameters.filePath, requestParameters.update, requestParameters.accessToken, requestParameters.librarySecret, requestParameters.updateDirectoryLabelsRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 用于更新文件的标签（Labels）或分类（Category）。 需要 admin 权限或 spaceAdmin 权限。 
     * @summary 更新文件标签或分类
     * @param {DirectoryApiUpdateFileLabelsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateFileLabels(requestParameters: DirectoryApiUpdateFileLabelsRequest, options?: RawAxiosRequestConfig) {
        return DirectoryApiFp(this.configuration).updateFileLabels(requestParameters.libraryId, requestParameters.spaceId, requestParameters.filePath, requestParameters.update, requestParameters.updateFileLabelsRequest, requestParameters.accessToken, requestParameters.librarySecret, options).then((request) => request(this.axios, this.basePath));
    }
}

export const CopyDirectoryConflictResolutionStrategyEnum = {
    Ask: 'ask',
    Rename: 'rename'
} as const;
export type CopyDirectoryConflictResolutionStrategyEnum = typeof CopyDirectoryConflictResolutionStrategyEnum[keyof typeof CopyDirectoryConflictResolutionStrategyEnum];
export const CreateDirectoryConflictResolutionStrategyEnum = {
    Ask: 'ask',
    Rename: 'rename'
} as const;
export type CreateDirectoryConflictResolutionStrategyEnum = typeof CreateDirectoryConflictResolutionStrategyEnum[keyof typeof CreateDirectoryConflictResolutionStrategyEnum];
export const CreateDirectoryWithInodeEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type CreateDirectoryWithInodeEnum = typeof CreateDirectoryWithInodeEnum[keyof typeof CreateDirectoryWithInodeEnum];
export const DeleteDirectoryPermanentEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type DeleteDirectoryPermanentEnum = typeof DeleteDirectoryPermanentEnum[keyof typeof DeleteDirectoryPermanentEnum];
export const InfoFileOrDirectoryInfoEnum = {
    NUMBER_1: 1
} as const;
export type InfoFileOrDirectoryInfoEnum = typeof InfoFileOrDirectoryInfoEnum[keyof typeof InfoFileOrDirectoryInfoEnum];
export const InfoFileOrDirectoryWithInodeEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type InfoFileOrDirectoryWithInodeEnum = typeof InfoFileOrDirectoryWithInodeEnum[keyof typeof InfoFileOrDirectoryWithInodeEnum];
export const InfoFileOrDirectoryWithFavoriteStatusEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type InfoFileOrDirectoryWithFavoriteStatusEnum = typeof InfoFileOrDirectoryWithFavoriteStatusEnum[keyof typeof InfoFileOrDirectoryWithFavoriteStatusEnum];
export const InfoFileOrDirectoryWithContentCasEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type InfoFileOrDirectoryWithContentCasEnum = typeof InfoFileOrDirectoryWithContentCasEnum[keyof typeof InfoFileOrDirectoryWithContentCasEnum];
export const ListDirectoryByMarkerEnum = {
    NUMBER_1: 1
} as const;
export type ListDirectoryByMarkerEnum = typeof ListDirectoryByMarkerEnum[keyof typeof ListDirectoryByMarkerEnum];
export const ListDirectoryOrderByEnum = {
    Name: 'name',
    ModificationTime: 'modificationTime',
    Size: 'size',
    CreationTime: 'creationTime',
    LocalCreationTime: 'localCreationTime'
} as const;
export type ListDirectoryOrderByEnum = typeof ListDirectoryOrderByEnum[keyof typeof ListDirectoryOrderByEnum];
export const ListDirectoryOrderByTypeEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListDirectoryOrderByTypeEnum = typeof ListDirectoryOrderByTypeEnum[keyof typeof ListDirectoryOrderByTypeEnum];
export const ListDirectoryFilterEnum = {
    OnlyDir: 'onlyDir',
    OnlyFile: 'onlyFile'
} as const;
export type ListDirectoryFilterEnum = typeof ListDirectoryFilterEnum[keyof typeof ListDirectoryFilterEnum];
export const ListDirectorySortTypeEnum = {
    Union: 'union'
} as const;
export type ListDirectorySortTypeEnum = typeof ListDirectorySortTypeEnum[keyof typeof ListDirectorySortTypeEnum];
export const ListDirectoryWithInodeEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type ListDirectoryWithInodeEnum = typeof ListDirectoryWithInodeEnum[keyof typeof ListDirectoryWithInodeEnum];
export const ListDirectoryWithFavoriteStatusEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type ListDirectoryWithFavoriteStatusEnum = typeof ListDirectoryWithFavoriteStatusEnum[keyof typeof ListDirectoryWithFavoriteStatusEnum];
export const ListDirectoryWithContentCasEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type ListDirectoryWithContentCasEnum = typeof ListDirectoryWithContentCasEnum[keyof typeof ListDirectoryWithContentCasEnum];
export const ListDirectoryByPageByPageEnum = {
    NUMBER_1: 1
} as const;
export type ListDirectoryByPageByPageEnum = typeof ListDirectoryByPageByPageEnum[keyof typeof ListDirectoryByPageByPageEnum];
export const ListDirectoryByPageOrderByEnum = {
    Name: 'name',
    ModificationTime: 'modificationTime',
    Size: 'size',
    CreationTime: 'creationTime',
    LocalCreationTime: 'localCreationTime'
} as const;
export type ListDirectoryByPageOrderByEnum = typeof ListDirectoryByPageOrderByEnum[keyof typeof ListDirectoryByPageOrderByEnum];
export const ListDirectoryByPageOrderByTypeEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListDirectoryByPageOrderByTypeEnum = typeof ListDirectoryByPageOrderByTypeEnum[keyof typeof ListDirectoryByPageOrderByTypeEnum];
export const ListDirectoryByPageFilterEnum = {
    OnlyDir: 'onlyDir',
    OnlyFile: 'onlyFile'
} as const;
export type ListDirectoryByPageFilterEnum = typeof ListDirectoryByPageFilterEnum[keyof typeof ListDirectoryByPageFilterEnum];
export const ListDirectoryByPageSortTypeEnum = {
    Union: 'union'
} as const;
export type ListDirectoryByPageSortTypeEnum = typeof ListDirectoryByPageSortTypeEnum[keyof typeof ListDirectoryByPageSortTypeEnum];
export const ListDirectoryByPageWithInodeEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type ListDirectoryByPageWithInodeEnum = typeof ListDirectoryByPageWithInodeEnum[keyof typeof ListDirectoryByPageWithInodeEnum];
export const ListDirectoryByPageWithFavoriteStatusEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type ListDirectoryByPageWithFavoriteStatusEnum = typeof ListDirectoryByPageWithFavoriteStatusEnum[keyof typeof ListDirectoryByPageWithFavoriteStatusEnum];
export const ListDirectoryByPageWithContentCasEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type ListDirectoryByPageWithContentCasEnum = typeof ListDirectoryByPageWithContentCasEnum[keyof typeof ListDirectoryByPageWithContentCasEnum];
export const MoveDirectoryConflictResolutionStrategyEnum = {
    Ask: 'ask',
    Rename: 'rename'
} as const;
export type MoveDirectoryConflictResolutionStrategyEnum = typeof MoveDirectoryConflictResolutionStrategyEnum[keyof typeof MoveDirectoryConflictResolutionStrategyEnum];
export const UpdateDirectoryLabelsUpdateEnum = {
    NUMBER_1: 1
} as const;
export type UpdateDirectoryLabelsUpdateEnum = typeof UpdateDirectoryLabelsUpdateEnum[keyof typeof UpdateDirectoryLabelsUpdateEnum];
export const UpdateFileLabelsUpdateEnum = {
    NUMBER_1: 1
} as const;
export type UpdateFileLabelsUpdateEnum = typeof UpdateFileLabelsUpdateEnum[keyof typeof UpdateFileLabelsUpdateEnum];
