/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateQuota201Response } from '../models';
// @ts-ignore
import type { CreateQuotaRequest } from '../models';
// @ts-ignore
import type { GetQuota200Response } from '../models';
// @ts-ignore
import type { GetQuotaInfo200Response } from '../models';
// @ts-ignore
import type { UpdateQuotaByIdRequest } from '../models';
// @ts-ignore
import type { UpdateQuotaRequest } from '../models';
/**
 * QuotaApi - axios parameter creator
 */
export const QuotaApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 用于创建配额。当在配置了配额的租户空间中上传即将超过配额的文件时，会返回 QuotaLimitReached 错误码；租户空间的剩余空间非实时更新，当系统负荷较高时可能会有比较大的更新延时，进而可能导致意外超出配额，如果配置了超额自动删除选项，可能进一步导致旧文件被删除；配额与租户空间是一对多的关系，即多个租户空间可以共享同一个配额，但每个租户空间只能设置一个配额。
         * @summary 创建配额
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {CreateQuotaRequest} createQuotaRequest 
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {string} [userId] 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createQuota: async (libraryId: string, createQuotaRequest: CreateQuotaRequest, accessToken?: string, librarySecret?: string, userId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'libraryId' is not null or undefined
            assertParamExists('createQuota', 'libraryId', libraryId)
            // verify required parameter 'createQuotaRequest' is not null or undefined
            assertParamExists('createQuota', 'createQuotaRequest', createQuotaRequest)
            const localVarPath = `/api/v1/quota/{LibraryId}`
                .replace(`{${"LibraryId"}}`, encodeURIComponent(String(libraryId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (accessToken !== undefined) {
                localVarQueryParameter['access_token'] = accessToken;
            }

            if (librarySecret !== undefined) {
                localVarQueryParameter['library_secret'] = librarySecret;
            }

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createQuotaRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 用于获取租户空间配额
         * @summary 获取租户空间配额
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {string} [userId] 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuota: async (libraryId: string, spaceId: string, accessToken?: string, librarySecret?: string, userId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'libraryId' is not null or undefined
            assertParamExists('getQuota', 'libraryId', libraryId)
            // verify required parameter 'spaceId' is not null or undefined
            assertParamExists('getQuota', 'spaceId', spaceId)
            const localVarPath = `/api/v1/quota/{LibraryId}/{SpaceId}`
                .replace(`{${"LibraryId"}}`, encodeURIComponent(String(libraryId)))
                .replace(`{${"SpaceId"}}`, encodeURIComponent(String(spaceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (accessToken !== undefined) {
                localVarQueryParameter['access_token'] = accessToken;
            }

            if (librarySecret !== undefined) {
                localVarQueryParameter['library_secret'] = librarySecret;
            }

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 用于获取租户配额信息
         * @summary 获取租户配额信息
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} quotaId 配额 ID，必选参数
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {string} [userId] 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuotaInfo: async (libraryId: string, quotaId: string, accessToken?: string, librarySecret?: string, userId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'libraryId' is not null or undefined
            assertParamExists('getQuotaInfo', 'libraryId', libraryId)
            // verify required parameter 'quotaId' is not null or undefined
            assertParamExists('getQuotaInfo', 'quotaId', quotaId)
            const localVarPath = `/api/v1/quota/{LibraryId}/{QuotaId}`
                .replace(`{${"LibraryId"}}`, encodeURIComponent(String(libraryId)))
                .replace(`{${"QuotaId"}}`, encodeURIComponent(String(quotaId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (accessToken !== undefined) {
                localVarQueryParameter['access_token'] = accessToken;
            }

            if (librarySecret !== undefined) {
                localVarQueryParameter['library_secret'] = librarySecret;
            }

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 用于修改配额
         * @summary 修改配额
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {UpdateQuotaRequest} updateQuotaRequest 
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {string} [userId] 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateQuota: async (libraryId: string, spaceId: string, updateQuotaRequest: UpdateQuotaRequest, accessToken?: string, librarySecret?: string, userId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'libraryId' is not null or undefined
            assertParamExists('updateQuota', 'libraryId', libraryId)
            // verify required parameter 'spaceId' is not null or undefined
            assertParamExists('updateQuota', 'spaceId', spaceId)
            // verify required parameter 'updateQuotaRequest' is not null or undefined
            assertParamExists('updateQuota', 'updateQuotaRequest', updateQuotaRequest)
            const localVarPath = `/api/v1/quota/{LibraryId}/{SpaceId}`
                .replace(`{${"LibraryId"}}`, encodeURIComponent(String(libraryId)))
                .replace(`{${"SpaceId"}}`, encodeURIComponent(String(spaceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (accessToken !== undefined) {
                localVarQueryParameter['access_token'] = accessToken;
            }

            if (librarySecret !== undefined) {
                localVarQueryParameter['library_secret'] = librarySecret;
            }

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateQuotaRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 用于根据配额 ID 修改配额
         * @summary 修改配额
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} quotaId 配额 ID，创建配额时会返回，也可以通过【获取租户空间配额】接口查询指定租户空间所在的配额 ID
         * @param {UpdateQuotaByIdRequest} updateQuotaByIdRequest 
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {string} [userId] 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateQuotaById: async (libraryId: string, quotaId: string, updateQuotaByIdRequest: UpdateQuotaByIdRequest, accessToken?: string, librarySecret?: string, userId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'libraryId' is not null or undefined
            assertParamExists('updateQuotaById', 'libraryId', libraryId)
            // verify required parameter 'quotaId' is not null or undefined
            assertParamExists('updateQuotaById', 'quotaId', quotaId)
            // verify required parameter 'updateQuotaByIdRequest' is not null or undefined
            assertParamExists('updateQuotaById', 'updateQuotaByIdRequest', updateQuotaByIdRequest)
            const localVarPath = `/api/v1/quota/{LibraryId}/{QuotaId}`
                .replace(`{${"LibraryId"}}`, encodeURIComponent(String(libraryId)))
                .replace(`{${"QuotaId"}}`, encodeURIComponent(String(quotaId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (accessToken !== undefined) {
                localVarQueryParameter['access_token'] = accessToken;
            }

            if (librarySecret !== undefined) {
                localVarQueryParameter['library_secret'] = librarySecret;
            }

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateQuotaByIdRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * QuotaApi - functional programming interface
 */
export const QuotaApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = QuotaApiAxiosParamCreator(configuration)
    return {
        /**
         * 用于创建配额。当在配置了配额的租户空间中上传即将超过配额的文件时，会返回 QuotaLimitReached 错误码；租户空间的剩余空间非实时更新，当系统负荷较高时可能会有比较大的更新延时，进而可能导致意外超出配额，如果配置了超额自动删除选项，可能进一步导致旧文件被删除；配额与租户空间是一对多的关系，即多个租户空间可以共享同一个配额，但每个租户空间只能设置一个配额。
         * @summary 创建配额
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {CreateQuotaRequest} createQuotaRequest 
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {string} [userId] 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createQuota(libraryId: string, createQuotaRequest: CreateQuotaRequest, accessToken?: string, librarySecret?: string, userId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateQuota201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createQuota(libraryId, createQuotaRequest, accessToken, librarySecret, userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuotaApi.createQuota']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 用于获取租户空间配额
         * @summary 获取租户空间配额
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {string} [userId] 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getQuota(libraryId: string, spaceId: string, accessToken?: string, librarySecret?: string, userId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetQuota200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getQuota(libraryId, spaceId, accessToken, librarySecret, userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuotaApi.getQuota']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 用于获取租户配额信息
         * @summary 获取租户配额信息
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} quotaId 配额 ID，必选参数
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {string} [userId] 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getQuotaInfo(libraryId: string, quotaId: string, accessToken?: string, librarySecret?: string, userId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetQuotaInfo200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getQuotaInfo(libraryId, quotaId, accessToken, librarySecret, userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuotaApi.getQuotaInfo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 用于修改配额
         * @summary 修改配额
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {UpdateQuotaRequest} updateQuotaRequest 
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {string} [userId] 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateQuota(libraryId: string, spaceId: string, updateQuotaRequest: UpdateQuotaRequest, accessToken?: string, librarySecret?: string, userId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateQuota(libraryId, spaceId, updateQuotaRequest, accessToken, librarySecret, userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuotaApi.updateQuota']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 用于根据配额 ID 修改配额
         * @summary 修改配额
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} quotaId 配额 ID，创建配额时会返回，也可以通过【获取租户空间配额】接口查询指定租户空间所在的配额 ID
         * @param {UpdateQuotaByIdRequest} updateQuotaByIdRequest 
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {string} [userId] 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateQuotaById(libraryId: string, quotaId: string, updateQuotaByIdRequest: UpdateQuotaByIdRequest, accessToken?: string, librarySecret?: string, userId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateQuotaById(libraryId, quotaId, updateQuotaByIdRequest, accessToken, librarySecret, userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuotaApi.updateQuotaById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * QuotaApi - factory interface
 */
export const QuotaApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = QuotaApiFp(configuration)
    return {
        /**
         * 用于创建配额。当在配置了配额的租户空间中上传即将超过配额的文件时，会返回 QuotaLimitReached 错误码；租户空间的剩余空间非实时更新，当系统负荷较高时可能会有比较大的更新延时，进而可能导致意外超出配额，如果配置了超额自动删除选项，可能进一步导致旧文件被删除；配额与租户空间是一对多的关系，即多个租户空间可以共享同一个配额，但每个租户空间只能设置一个配额。
         * @summary 创建配额
         * @param {QuotaApiCreateQuotaRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createQuota(requestParameters: QuotaApiCreateQuotaRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateQuota201Response> {
            return localVarFp.createQuota(requestParameters.libraryId, requestParameters.createQuotaRequest, requestParameters.accessToken, requestParameters.librarySecret, requestParameters.userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 用于获取租户空间配额
         * @summary 获取租户空间配额
         * @param {QuotaApiGetQuotaRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuota(requestParameters: QuotaApiGetQuotaRequest, options?: RawAxiosRequestConfig): AxiosPromise<GetQuota200Response> {
            return localVarFp.getQuota(requestParameters.libraryId, requestParameters.spaceId, requestParameters.accessToken, requestParameters.librarySecret, requestParameters.userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 用于获取租户配额信息
         * @summary 获取租户配额信息
         * @param {QuotaApiGetQuotaInfoRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuotaInfo(requestParameters: QuotaApiGetQuotaInfoRequest, options?: RawAxiosRequestConfig): AxiosPromise<GetQuotaInfo200Response> {
            return localVarFp.getQuotaInfo(requestParameters.libraryId, requestParameters.quotaId, requestParameters.accessToken, requestParameters.librarySecret, requestParameters.userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 用于修改配额
         * @summary 修改配额
         * @param {QuotaApiUpdateQuotaRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateQuota(requestParameters: QuotaApiUpdateQuotaRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.updateQuota(requestParameters.libraryId, requestParameters.spaceId, requestParameters.updateQuotaRequest, requestParameters.accessToken, requestParameters.librarySecret, requestParameters.userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 用于根据配额 ID 修改配额
         * @summary 修改配额
         * @param {QuotaApiUpdateQuotaByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateQuotaById(requestParameters: QuotaApiUpdateQuotaByIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.updateQuotaById(requestParameters.libraryId, requestParameters.quotaId, requestParameters.updateQuotaByIdRequest, requestParameters.accessToken, requestParameters.librarySecret, requestParameters.userId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createQuota operation in QuotaApi.
 */
export interface QuotaApiCreateQuotaRequest {
    /**
     * 媒体库 ID，必选参数
     */
    readonly libraryId: string

    readonly createQuotaRequest: CreateQuotaRequest

    /**
     * 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
     */
    readonly accessToken?: string

    /**
     * 访问媒体库密钥，可选参数
     */
    readonly librarySecret?: string

    /**
     * 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
     */
    readonly userId?: string
}

/**
 * Request parameters for getQuota operation in QuotaApi.
 */
export interface QuotaApiGetQuotaRequest {
    /**
     * 媒体库 ID，必选参数
     */
    readonly libraryId: string

    /**
     * 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
     */
    readonly spaceId: string

    /**
     * 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
     */
    readonly accessToken?: string

    /**
     * 访问媒体库密钥，可选参数
     */
    readonly librarySecret?: string

    /**
     * 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
     */
    readonly userId?: string
}

/**
 * Request parameters for getQuotaInfo operation in QuotaApi.
 */
export interface QuotaApiGetQuotaInfoRequest {
    /**
     * 媒体库 ID，必选参数
     */
    readonly libraryId: string

    /**
     * 配额 ID，必选参数
     */
    readonly quotaId: string

    /**
     * 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
     */
    readonly accessToken?: string

    /**
     * 访问媒体库密钥，可选参数
     */
    readonly librarySecret?: string

    /**
     * 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
     */
    readonly userId?: string
}

/**
 * Request parameters for updateQuota operation in QuotaApi.
 */
export interface QuotaApiUpdateQuotaRequest {
    /**
     * 媒体库 ID，必选参数
     */
    readonly libraryId: string

    /**
     * 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
     */
    readonly spaceId: string

    readonly updateQuotaRequest: UpdateQuotaRequest

    /**
     * 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
     */
    readonly accessToken?: string

    /**
     * 访问媒体库密钥，可选参数
     */
    readonly librarySecret?: string

    /**
     * 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
     */
    readonly userId?: string
}

/**
 * Request parameters for updateQuotaById operation in QuotaApi.
 */
export interface QuotaApiUpdateQuotaByIdRequest {
    /**
     * 媒体库 ID，必选参数
     */
    readonly libraryId: string

    /**
     * 配额 ID，创建配额时会返回，也可以通过【获取租户空间配额】接口查询指定租户空间所在的配额 ID
     */
    readonly quotaId: string

    readonly updateQuotaByIdRequest: UpdateQuotaByIdRequest

    /**
     * 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
     */
    readonly accessToken?: string

    /**
     * 访问媒体库密钥，可选参数
     */
    readonly librarySecret?: string

    /**
     * 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
     */
    readonly userId?: string
}

/**
 * QuotaApi - object-oriented interface
 */
export class QuotaApi extends BaseAPI {
    /**
     * 用于创建配额。当在配置了配额的租户空间中上传即将超过配额的文件时，会返回 QuotaLimitReached 错误码；租户空间的剩余空间非实时更新，当系统负荷较高时可能会有比较大的更新延时，进而可能导致意外超出配额，如果配置了超额自动删除选项，可能进一步导致旧文件被删除；配额与租户空间是一对多的关系，即多个租户空间可以共享同一个配额，但每个租户空间只能设置一个配额。
     * @summary 创建配额
     * @param {QuotaApiCreateQuotaRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createQuota(requestParameters: QuotaApiCreateQuotaRequest, options?: RawAxiosRequestConfig) {
        return QuotaApiFp(this.configuration).createQuota(requestParameters.libraryId, requestParameters.createQuotaRequest, requestParameters.accessToken, requestParameters.librarySecret, requestParameters.userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 用于获取租户空间配额
     * @summary 获取租户空间配额
     * @param {QuotaApiGetQuotaRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getQuota(requestParameters: QuotaApiGetQuotaRequest, options?: RawAxiosRequestConfig) {
        return QuotaApiFp(this.configuration).getQuota(requestParameters.libraryId, requestParameters.spaceId, requestParameters.accessToken, requestParameters.librarySecret, requestParameters.userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 用于获取租户配额信息
     * @summary 获取租户配额信息
     * @param {QuotaApiGetQuotaInfoRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getQuotaInfo(requestParameters: QuotaApiGetQuotaInfoRequest, options?: RawAxiosRequestConfig) {
        return QuotaApiFp(this.configuration).getQuotaInfo(requestParameters.libraryId, requestParameters.quotaId, requestParameters.accessToken, requestParameters.librarySecret, requestParameters.userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 用于修改配额
     * @summary 修改配额
     * @param {QuotaApiUpdateQuotaRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateQuota(requestParameters: QuotaApiUpdateQuotaRequest, options?: RawAxiosRequestConfig) {
        return QuotaApiFp(this.configuration).updateQuota(requestParameters.libraryId, requestParameters.spaceId, requestParameters.updateQuotaRequest, requestParameters.accessToken, requestParameters.librarySecret, requestParameters.userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 用于根据配额 ID 修改配额
     * @summary 修改配额
     * @param {QuotaApiUpdateQuotaByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateQuotaById(requestParameters: QuotaApiUpdateQuotaByIdRequest, options?: RawAxiosRequestConfig) {
        return QuotaApiFp(this.configuration).updateQuotaById(requestParameters.libraryId, requestParameters.quotaId, requestParameters.updateQuotaByIdRequest, requestParameters.accessToken, requestParameters.librarySecret, requestParameters.userId, options).then((request) => request(this.axios, this.basePath));
    }
}

