/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ListRecentlyUsedFile200Response } from '../models';
// @ts-ignore
import type { ListRecentlyUsedFileRequest } from '../models';
/**
 * RecentApi - axios parameter creator
 */
export const RecentApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 用于查看最近使用文件列表，仅文件预览及文件编辑操作会被记录到最近使用文件列表中，返回的文件列表按照操作时间进行倒序排列
         * @summary 查看最近使用文件列表
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {ListRecentlyUsedFileRequest} [listRecentlyUsedFileRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listRecentlyUsedFile: async (libraryId: string, spaceId: string, accessToken?: string, librarySecret?: string, listRecentlyUsedFileRequest?: ListRecentlyUsedFileRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'libraryId' is not null or undefined
            assertParamExists('listRecentlyUsedFile', 'libraryId', libraryId)
            // verify required parameter 'spaceId' is not null or undefined
            assertParamExists('listRecentlyUsedFile', 'spaceId', spaceId)
            const localVarPath = `/api/v1/recent/{LibraryId}/{SpaceId}/recently-used-file`
                .replace(`{${"LibraryId"}}`, encodeURIComponent(String(libraryId)))
                .replace(`{${"SpaceId"}}`, encodeURIComponent(String(spaceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (accessToken !== undefined) {
                localVarQueryParameter['access_token'] = accessToken;
            }

            if (librarySecret !== undefined) {
                localVarQueryParameter['library_secret'] = librarySecret;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(listRecentlyUsedFileRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RecentApi - functional programming interface
 */
export const RecentApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RecentApiAxiosParamCreator(configuration)
    return {
        /**
         * 用于查看最近使用文件列表，仅文件预览及文件编辑操作会被记录到最近使用文件列表中，返回的文件列表按照操作时间进行倒序排列
         * @summary 查看最近使用文件列表
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {ListRecentlyUsedFileRequest} [listRecentlyUsedFileRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listRecentlyUsedFile(libraryId: string, spaceId: string, accessToken?: string, librarySecret?: string, listRecentlyUsedFileRequest?: ListRecentlyUsedFileRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListRecentlyUsedFile200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listRecentlyUsedFile(libraryId, spaceId, accessToken, librarySecret, listRecentlyUsedFileRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecentApi.listRecentlyUsedFile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RecentApi - factory interface
 */
export const RecentApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RecentApiFp(configuration)
    return {
        /**
         * 用于查看最近使用文件列表，仅文件预览及文件编辑操作会被记录到最近使用文件列表中，返回的文件列表按照操作时间进行倒序排列
         * @summary 查看最近使用文件列表
         * @param {RecentApiListRecentlyUsedFileRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listRecentlyUsedFile(requestParameters: RecentApiListRecentlyUsedFileRequest, options?: RawAxiosRequestConfig): AxiosPromise<ListRecentlyUsedFile200Response> {
            return localVarFp.listRecentlyUsedFile(requestParameters.libraryId, requestParameters.spaceId, requestParameters.accessToken, requestParameters.librarySecret, requestParameters.listRecentlyUsedFileRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for listRecentlyUsedFile operation in RecentApi.
 */
export interface RecentApiListRecentlyUsedFileRequest {
    /**
     * 媒体库 ID，必选参数
     */
    readonly libraryId: string

    /**
     * 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
     */
    readonly spaceId: string

    /**
     * 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
     */
    readonly accessToken?: string

    /**
     * 访问媒体库密钥，可选参数
     */
    readonly librarySecret?: string

    readonly listRecentlyUsedFileRequest?: ListRecentlyUsedFileRequest
}

/**
 * RecentApi - object-oriented interface
 */
export class RecentApi extends BaseAPI {
    /**
     * 用于查看最近使用文件列表，仅文件预览及文件编辑操作会被记录到最近使用文件列表中，返回的文件列表按照操作时间进行倒序排列
     * @summary 查看最近使用文件列表
     * @param {RecentApiListRecentlyUsedFileRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listRecentlyUsedFile(requestParameters: RecentApiListRecentlyUsedFileRequest, options?: RawAxiosRequestConfig) {
        return RecentApiFp(this.configuration).listRecentlyUsedFile(requestParameters.libraryId, requestParameters.spaceId, requestParameters.accessToken, requestParameters.librarySecret, requestParameters.listRecentlyUsedFileRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

