/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { SearchFs200Response } from '../models';
// @ts-ignore
import type { SearchFsRequest } from '../models';
// @ts-ignore
import type { SearchFsStats200Response } from '../models';
// @ts-ignore
import type { SearchFsStatsRequest } from '../models';
/**
 * SearchApi - axios parameter creator
 */
export const SearchApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 用于搜索目录与文件。 使用本接口搜索时，如果在返回时有部分或全部搜索结果，则返回已搜索出的结果的第一页（每页 20 个），如果暂未搜索到结果则返回空数组，因此该接口实际返回的 contents 数量可能为 0 到 20 之间不等，且是否还有更多搜索结果，不应参考 contents 的数量，而应参考 nextMarker 字段； 当需要获取后续页时，传入marker参数进行翻页； 本接口QPS使用上限为10，此接口不可用于业务的高频操作页面，比如空间首页列表的查询等，如有更大QPS的需求请提工单联系智能媒资托管团队； 
         * @summary 搜索目录与文件
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {string} [userId] 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
         * @param {string} [marker] 用于顺序列出分页的标识，可选参数，建议将marker放入请求体中传入
         * @param {number} [limit] 用于顺序列出分页时本地列出的项目数限制，可选参数，取值范围[1,100]
         * @param {SearchFsWithFavoriteStatusEnum} [withFavoriteStatus] 0 或 1，是否返回收藏状态，可选，默认不返回
         * @param {SearchFsRequest} [searchFsRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchFs: async (libraryId: string, spaceId: string, accessToken?: string, librarySecret?: string, userId?: string, marker?: string, limit?: number, withFavoriteStatus?: SearchFsWithFavoriteStatusEnum, searchFsRequest?: SearchFsRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'libraryId' is not null or undefined
            assertParamExists('searchFs', 'libraryId', libraryId)
            // verify required parameter 'spaceId' is not null or undefined
            assertParamExists('searchFs', 'spaceId', spaceId)
            const localVarPath = `/api/v1/search/{LibraryId}/{SpaceId}/search-fs`
                .replace(`{${"LibraryId"}}`, encodeURIComponent(String(libraryId)))
                .replace(`{${"SpaceId"}}`, encodeURIComponent(String(spaceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (accessToken !== undefined) {
                localVarQueryParameter['access_token'] = accessToken;
            }

            if (librarySecret !== undefined) {
                localVarQueryParameter['library_secret'] = librarySecret;
            }

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }

            if (marker !== undefined) {
                localVarQueryParameter['marker'] = marker;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (withFavoriteStatus !== undefined) {
                localVarQueryParameter['with_favorite_status'] = withFavoriteStatus;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(searchFsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 用于对目录与文件进行聚合统计，支持按指定字段分组并对分组结果进行求和、计数等子统计操作。典型场景如：按文件后缀分组统计文件大小总和、按文件分类统计文件数量等。 本接口基于搜索条件对文件进行聚合统计，不返回文件列表，仅返回统计结果； 支持与搜索接口相同的筛选条件，可在筛选范围内进行统计； 单次请求最多支持 5 个聚合统计项； 每个聚合统计项支持嵌套一层子聚合（如 group by extName + sum(size)）； 分组聚合（group）默认最多返回 2000 个分组； 本接口 QPS 使用上限为 10； 
         * @summary 搜索目录与文件统计
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {SearchFsStatsRequest} searchFsStatsRequest 
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {string} [userId] 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchFsStats: async (libraryId: string, spaceId: string, searchFsStatsRequest: SearchFsStatsRequest, accessToken?: string, librarySecret?: string, userId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'libraryId' is not null or undefined
            assertParamExists('searchFsStats', 'libraryId', libraryId)
            // verify required parameter 'spaceId' is not null or undefined
            assertParamExists('searchFsStats', 'spaceId', spaceId)
            // verify required parameter 'searchFsStatsRequest' is not null or undefined
            assertParamExists('searchFsStats', 'searchFsStatsRequest', searchFsStatsRequest)
            const localVarPath = `/api/v1/search/{LibraryId}/{SpaceId}/search-fs-stats`
                .replace(`{${"LibraryId"}}`, encodeURIComponent(String(libraryId)))
                .replace(`{${"SpaceId"}}`, encodeURIComponent(String(spaceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (accessToken !== undefined) {
                localVarQueryParameter['access_token'] = accessToken;
            }

            if (librarySecret !== undefined) {
                localVarQueryParameter['library_secret'] = librarySecret;
            }

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(searchFsStatsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SearchApi - functional programming interface
 */
export const SearchApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SearchApiAxiosParamCreator(configuration)
    return {
        /**
         * 用于搜索目录与文件。 使用本接口搜索时，如果在返回时有部分或全部搜索结果，则返回已搜索出的结果的第一页（每页 20 个），如果暂未搜索到结果则返回空数组，因此该接口实际返回的 contents 数量可能为 0 到 20 之间不等，且是否还有更多搜索结果，不应参考 contents 的数量，而应参考 nextMarker 字段； 当需要获取后续页时，传入marker参数进行翻页； 本接口QPS使用上限为10，此接口不可用于业务的高频操作页面，比如空间首页列表的查询等，如有更大QPS的需求请提工单联系智能媒资托管团队； 
         * @summary 搜索目录与文件
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {string} [userId] 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
         * @param {string} [marker] 用于顺序列出分页的标识，可选参数，建议将marker放入请求体中传入
         * @param {number} [limit] 用于顺序列出分页时本地列出的项目数限制，可选参数，取值范围[1,100]
         * @param {SearchFsWithFavoriteStatusEnum} [withFavoriteStatus] 0 或 1，是否返回收藏状态，可选，默认不返回
         * @param {SearchFsRequest} [searchFsRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchFs(libraryId: string, spaceId: string, accessToken?: string, librarySecret?: string, userId?: string, marker?: string, limit?: number, withFavoriteStatus?: SearchFsWithFavoriteStatusEnum, searchFsRequest?: SearchFsRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SearchFs200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchFs(libraryId, spaceId, accessToken, librarySecret, userId, marker, limit, withFavoriteStatus, searchFsRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SearchApi.searchFs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 用于对目录与文件进行聚合统计，支持按指定字段分组并对分组结果进行求和、计数等子统计操作。典型场景如：按文件后缀分组统计文件大小总和、按文件分类统计文件数量等。 本接口基于搜索条件对文件进行聚合统计，不返回文件列表，仅返回统计结果； 支持与搜索接口相同的筛选条件，可在筛选范围内进行统计； 单次请求最多支持 5 个聚合统计项； 每个聚合统计项支持嵌套一层子聚合（如 group by extName + sum(size)）； 分组聚合（group）默认最多返回 2000 个分组； 本接口 QPS 使用上限为 10； 
         * @summary 搜索目录与文件统计
         * @param {string} libraryId 媒体库 ID，必选参数
         * @param {string} spaceId 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
         * @param {SearchFsStatsRequest} searchFsStatsRequest 
         * @param {string} [accessToken] 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
         * @param {string} [librarySecret] 访问媒体库密钥，可选参数
         * @param {string} [userId] 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchFsStats(libraryId: string, spaceId: string, searchFsStatsRequest: SearchFsStatsRequest, accessToken?: string, librarySecret?: string, userId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SearchFsStats200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchFsStats(libraryId, spaceId, searchFsStatsRequest, accessToken, librarySecret, userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SearchApi.searchFsStats']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SearchApi - factory interface
 */
export const SearchApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SearchApiFp(configuration)
    return {
        /**
         * 用于搜索目录与文件。 使用本接口搜索时，如果在返回时有部分或全部搜索结果，则返回已搜索出的结果的第一页（每页 20 个），如果暂未搜索到结果则返回空数组，因此该接口实际返回的 contents 数量可能为 0 到 20 之间不等，且是否还有更多搜索结果，不应参考 contents 的数量，而应参考 nextMarker 字段； 当需要获取后续页时，传入marker参数进行翻页； 本接口QPS使用上限为10，此接口不可用于业务的高频操作页面，比如空间首页列表的查询等，如有更大QPS的需求请提工单联系智能媒资托管团队； 
         * @summary 搜索目录与文件
         * @param {SearchApiSearchFsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchFs(requestParameters: SearchApiSearchFsRequest, options?: RawAxiosRequestConfig): AxiosPromise<SearchFs200Response> {
            return localVarFp.searchFs(requestParameters.libraryId, requestParameters.spaceId, requestParameters.accessToken, requestParameters.librarySecret, requestParameters.userId, requestParameters.marker, requestParameters.limit, requestParameters.withFavoriteStatus, requestParameters.searchFsRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 用于对目录与文件进行聚合统计，支持按指定字段分组并对分组结果进行求和、计数等子统计操作。典型场景如：按文件后缀分组统计文件大小总和、按文件分类统计文件数量等。 本接口基于搜索条件对文件进行聚合统计，不返回文件列表，仅返回统计结果； 支持与搜索接口相同的筛选条件，可在筛选范围内进行统计； 单次请求最多支持 5 个聚合统计项； 每个聚合统计项支持嵌套一层子聚合（如 group by extName + sum(size)）； 分组聚合（group）默认最多返回 2000 个分组； 本接口 QPS 使用上限为 10； 
         * @summary 搜索目录与文件统计
         * @param {SearchApiSearchFsStatsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchFsStats(requestParameters: SearchApiSearchFsStatsRequest, options?: RawAxiosRequestConfig): AxiosPromise<SearchFsStats200Response> {
            return localVarFp.searchFsStats(requestParameters.libraryId, requestParameters.spaceId, requestParameters.searchFsStatsRequest, requestParameters.accessToken, requestParameters.librarySecret, requestParameters.userId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for searchFs operation in SearchApi.
 */
export interface SearchApiSearchFsRequest {
    /**
     * 媒体库 ID，必选参数
     */
    readonly libraryId: string

    /**
     * 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
     */
    readonly spaceId: string

    /**
     * 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
     */
    readonly accessToken?: string

    /**
     * 访问媒体库密钥，可选参数
     */
    readonly librarySecret?: string

    /**
     * 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
     */
    readonly userId?: string

    /**
     * 用于顺序列出分页的标识，可选参数，建议将marker放入请求体中传入
     */
    readonly marker?: string

    /**
     * 用于顺序列出分页时本地列出的项目数限制，可选参数，取值范围[1,100]
     */
    readonly limit?: number

    /**
     * 0 或 1，是否返回收藏状态，可选，默认不返回
     */
    readonly withFavoriteStatus?: SearchFsWithFavoriteStatusEnum

    readonly searchFsRequest?: SearchFsRequest
}

/**
 * Request parameters for searchFsStats operation in SearchApi.
 */
export interface SearchApiSearchFsStatsRequest {
    /**
     * 媒体库 ID，必选参数
     */
    readonly libraryId: string

    /**
     * 空间 ID，如果媒体库为单租户模式，则该参数固定为连字符(-)；如果媒体库为多租户模式，则必须指定该参数
     */
    readonly spaceId: string

    readonly searchFsStatsRequest: SearchFsStatsRequest

    /**
     * 访问令牌，对于公有读媒体库或租户空间，可不指定该参数，否则必须指定该参数
     */
    readonly accessToken?: string

    /**
     * 访问媒体库密钥，可选参数
     */
    readonly librarySecret?: string

    /**
     * 用户身份识别，当访问令牌对应的权限为管理员权限且申请访问令牌时的用户身份识别为空时用来临时指定用户身份，详情请参阅生成访问令牌接口，可选参数
     */
    readonly userId?: string
}

/**
 * SearchApi - object-oriented interface
 */
export class SearchApi extends BaseAPI {
    /**
     * 用于搜索目录与文件。 使用本接口搜索时，如果在返回时有部分或全部搜索结果，则返回已搜索出的结果的第一页（每页 20 个），如果暂未搜索到结果则返回空数组，因此该接口实际返回的 contents 数量可能为 0 到 20 之间不等，且是否还有更多搜索结果，不应参考 contents 的数量，而应参考 nextMarker 字段； 当需要获取后续页时，传入marker参数进行翻页； 本接口QPS使用上限为10，此接口不可用于业务的高频操作页面，比如空间首页列表的查询等，如有更大QPS的需求请提工单联系智能媒资托管团队； 
     * @summary 搜索目录与文件
     * @param {SearchApiSearchFsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public searchFs(requestParameters: SearchApiSearchFsRequest, options?: RawAxiosRequestConfig) {
        return SearchApiFp(this.configuration).searchFs(requestParameters.libraryId, requestParameters.spaceId, requestParameters.accessToken, requestParameters.librarySecret, requestParameters.userId, requestParameters.marker, requestParameters.limit, requestParameters.withFavoriteStatus, requestParameters.searchFsRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 用于对目录与文件进行聚合统计，支持按指定字段分组并对分组结果进行求和、计数等子统计操作。典型场景如：按文件后缀分组统计文件大小总和、按文件分类统计文件数量等。 本接口基于搜索条件对文件进行聚合统计，不返回文件列表，仅返回统计结果； 支持与搜索接口相同的筛选条件，可在筛选范围内进行统计； 单次请求最多支持 5 个聚合统计项； 每个聚合统计项支持嵌套一层子聚合（如 group by extName + sum(size)）； 分组聚合（group）默认最多返回 2000 个分组； 本接口 QPS 使用上限为 10； 
     * @summary 搜索目录与文件统计
     * @param {SearchApiSearchFsStatsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public searchFsStats(requestParameters: SearchApiSearchFsStatsRequest, options?: RawAxiosRequestConfig) {
        return SearchApiFp(this.configuration).searchFsStats(requestParameters.libraryId, requestParameters.spaceId, requestParameters.searchFsStatsRequest, requestParameters.accessToken, requestParameters.librarySecret, requestParameters.userId, options).then((request) => request(this.axios, this.basePath));
    }
}

export const SearchFsWithFavoriteStatusEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type SearchFsWithFavoriteStatusEnum = typeof SearchFsWithFavoriteStatusEnum[keyof typeof SearchFsWithFavoriteStatusEnum];
