/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface BatchDeleteRequestInner {
    /**
     * 被删除的目录、相簿或文件路径
     */
    'path': string;
    /**
     * 当开启回收站时，指定移入回收站或永久删除，默认 false
     */
    'permanent'?: boolean;
}

