/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CheckFileDeletion200Response {
    /**
     * 文件删除的原因
     */
    'reason'?: CheckFileDeletion200ResponseReasonEnum;
    /**
     * 文件删除的时间
     */
    'deletedAt'?: string;
    /**
     * quota 超限删除流水保留天数
     */
    'quotaCleanupRecordRetentionDays'?: number;
}

export const CheckFileDeletion200ResponseReasonEnum = {
    RemovedByQuota: 'RemovedByQuota',
    Unknown: 'Unknown'
} as const;

export type CheckFileDeletion200ResponseReasonEnum = typeof CheckFileDeletion200ResponseReasonEnum[keyof typeof CheckFileDeletion200ResponseReasonEnum];


