/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ConfirmM3u8UploadRequestPlaylist } from './confirm-m3u8-upload-request-playlist';
// May contain unused imports in some cases
// @ts-ignore
import type { ConfirmM3u8UploadRequestSegmentsInner } from './confirm-m3u8-upload-request-segments-inner';

export interface ConfirmM3u8UploadRequest {
    'playlist'?: ConfirmM3u8UploadRequestPlaylist;
    /**
     * 分片文件列表，分批传入
     */
    'segments'?: Array<ConfirmM3u8UploadRequestSegmentsInner>;
}

