/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 分享配置对象
 */
export interface CreateShareRequestConfig {
    /**
     * 是否永久有效，默认为 false
     */
    'isPermanent'?: boolean;
    /**
     * 过期时间，ISO 8601 格式，当 isPermanent 为 false 时必选
     */
    'expireTime'?: string;
    /**
     * 提取码（6位以下）
     */
    'extractionCode'?: string;
    /**
     * 是否允许预览，默认为 false
     */
    'canPreview'?: boolean;
    /**
     * 是否允许下载，默认为 false
     */
    'canDownload'?: boolean;
    /**
     * 是否允许保存到网盘，默认为 false
     */
    'canSaveToNetdisk'?: boolean;
    /**
     * 是否禁止匿名用户访问，默认为 false
     */
    'forbidAnonymousUser'?: boolean;
    /**
     * 预览次数限制（canPreview 为 false 时，忽略此参数）
     */
    'previewLimit'?: number;
    /**
     * 下载次数限制（canDownload 为 false 时，忽略此参数）
     */
    'downloadLimit'?: number;
    /**
     * 访问用户数限制（设置时禁止匿名用户访问，否则冲突报错）
     */
    'userLimit'?: number;
    /**
     * 指定分享给的用户列表（设置时禁止匿名用户访问，否则冲突报错）
     */
    'shareToUsers'?: Array<string>;
}

