/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CreateTranscodeTask200Response {
    /**
     * 转码任务 ID，可通过查询任务接口检查转码进度
     */
    'taskId'?: number;
}

