/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CreateDirectory201Response {
    /**
     * 最终的目录或相簿路径，可能因自动重命名与指定路径不同
     */
    'path'?: Array<string>;
    /**
     * 最后一级文件目录ID
     */
    'inode'?: string;
    /**
     * 目录创建时间
     */
    'creationTime'?: string;
    /**
     * 创建时传入的自定义元数据（key 带 x-smh-meta- 前缀），未设置时不返回该字段
     */
    'metaData'?: { [key: string]: string; };
    /**
     * 创建时传入的标签列表，未设置时不返回该字段
     */
    'labels'?: Array<string>;
    /**
     * 创建时传入的本地创建时间，未设置时不返回该字段
     */
    'localCreationTime'?: string;
    /**
     * 创建时传入的本地修改时间，未设置时不返回该字段
     */
    'localModificationTime'?: string;
}

