/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreateShareRequestConfig } from './create-share-request-config';

export interface CreateShareRequest {
    /**
     * 分享名称
     */
    'name': string;
    /**
     * 要分享的文件或目录路径数组，最多 1000 条
     */
    'filePath': Array<string>;
    'config'?: CreateShareRequestConfig;
}

