/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 文件信息（仅当请求参数 with_file_info=1 时返回）
 */
export interface GetShareDetail200ResponseFileInfo {
    /**
     * 文件名（随机返回一个分享里面的文件/文件夹的 name）
     */
    'fileName'?: string;
    /**
     * 文件类型（文件或者文件夹）
     */
    'fileType'?: string;
    /**
     * 文件大小，文件为目录时为空
     */
    'size'?: string;
}

