/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetFileUpload200ResponsePartsInner } from './get-file-upload200-response-parts-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { GetFileUpload200ResponseUploadPartInfo } from './get-file-upload200-response-upload-part-info';

export interface GetFileUpload200Response {
    /**
     * 布尔型，代表当前上传任务是否为已完成
     */
    'confirmed'?: boolean;
    /**
     * 字符串数组 或 null，如果是字符串数组则表示最终的文件路径，数组中的最后一个元素代表最终的文件名，其他元素代表每一级目录名，因为可能存在同名文件自动重命名，所以这里的最终路径可能不等同于开始上传时指定的路径；如果是 null 则表示该文件所在的目录或其某个父级目录已被删除，该文件已经无法访问
     */
    'path'?: Array<string>;
    /**
     * 文件类型
     */
    'type'?: string;
    /**
     * 上传任务创建时间
     */
    'creationTime'?: string;
    /**
     * 文件名冲突时的处理方式，ask冲突时返回 HTTP 409 Conflict 及 SameNameDirectoryOrFileExists 错误码，rename冲突时自动重命名文件，overwrite如果冲突目标为目录时返回 HTTP 409 Conflict 及 SameNameDirectoryOrFileExists 错误码，否则覆盖已有文件
     */
    'conflictResolutionStrategy'?: GetFileUpload200ResponseConflictResolutionStrategyEnum;
    /**
     * 是否强制覆盖同路径文件
     */
    'force'?: boolean;
    /**
     * 可用域名数量
     */
    'availableDomainNum'?: number;
    /**
     * 如果为分块上传则返回该字段，作为实际文件上传时需指定的请求参数；否则不返回该字段
     */
    'uploadId'?: string;
    /**
     * 如果为分块上传则返回该字段，包含已上传的分块信息；否则不返回该字段
     */
    'parts'?: Array<GetFileUpload200ResponsePartsInner>;
    'uploadPartInfo'?: GetFileUpload200ResponseUploadPartInfo;
}

export const GetFileUpload200ResponseConflictResolutionStrategyEnum = {
    Ask: 'ask',
    Rename: 'rename',
    Overwrite: 'overwrite'
} as const;

export type GetFileUpload200ResponseConflictResolutionStrategyEnum = typeof GetFileUpload200ResponseConflictResolutionStrategyEnum[keyof typeof GetFileUpload200ResponseConflictResolutionStrategyEnum];


