/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface GetDeltaCursor200Response {
    /**
     * 当前最新的增量游标，可作为增量查询变动日志接口的起始点，调用方应将其视为不透明标记进行保存和传递
     */
    'cursor'?: string;
}

