/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface GetContentsView200ResponseContentsInner {
    /**
     * 目录或相簿名或文件名
     */
    'name'?: string;
    /**
     * 文件路径，仅当设置了withPath为true时返回
     */
    'path'?: Array<string>;
    /**
     * 文件目录ID
     */
    'inode'?: string;
    /**
     * 条目类型：dir-目录或相簿，file-文件（仅文件类型媒体库），image-图片（仅媒体类型媒体库），video-视频（仅媒体类型媒体库），symlink-符号链接，virtual-虚拟文件
     */
    'type'?: GetContentsView200ResponseContentsInnerTypeEnum;
    /**
     * 创建时间或上传时间
     */
    'creationTime'?: string;
    /**
     * 最近修改时间
     */
    'modificationTime'?: string;
    /**
     * 版本号
     */
    'versionId'?: number;
    /**
     * 媒体类型
     */
    'contentType'?: string;
    /**
     * 文件大小
     */
    'size'?: string;
    /**
     * ETag
     */
    'eTag'?: string;
    /**
     * CRC64校验值
     */
    'crc64'?: string;
    /**
     * 文件元数据信息
     */
    'metaData'?: { [key: string]: string; };
    /**
     * 是否可通过wps预览
     */
    'previewByDoc'?: boolean;
    /**
     * 是否可通过万象预览
     */
    'previewByCI'?: boolean;
    /**
     * 是否可用预览图作为icon
     */
    'previewAsIcon'?: boolean;
    /**
     * 文件类型
     */
    'fileType'?: string;
    /**
     * 简易文件标签列表
     */
    'labels'?: Array<string>;
    /**
     * 文件自定义分类
     */
    'category'?: string;
    /**
     * 本地创建时间
     */
    'localCreationTime'?: string;
    /**
     * 本地修改时间
     */
    'localModificationTime'?: string;
}

export const GetContentsView200ResponseContentsInnerTypeEnum = {
    Dir: 'dir',
    File: 'file',
    Image: 'image',
    Video: 'video',
    Symlink: 'symlink',
    Virtual: 'virtual'
} as const;

export type GetContentsView200ResponseContentsInnerTypeEnum = typeof GetContentsView200ResponseContentsInnerTypeEnum[keyof typeof GetContentsView200ResponseContentsInnerTypeEnum];


