/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface InfoFileOrDirectory200Response {
    /**
     * 完整路径
     */
    'path'?: Array<string>;
    /**
     * 文件目录 ID
     */
    'inode'?: string;
    /**
     * 目录或相簿名或文件名
     */
    'name'?: string;
    /**
     * 条目类型：dir-目录或相簿，file-文件（仅文件类型媒体库），image-图片（仅媒体类型媒体库），video-视频（仅媒体类型媒体库），symlink-符号链接，virtual-虚拟文件
     */
    'type'?: InfoFileOrDirectory200ResponseTypeEnum;
    /**
     * 创建人 ID
     */
    'userId'?: string;
    /**
     * ISO 8601格式的日期与时间字符串，表示目录或相簿的创建时间或文件的上传时间
     */
    'creationTime'?: string;
    /**
     * 文件最近一次被覆盖的时间，或者目录内最近一次增删子目录或文件的时间
     */
    'modificationTime'?: string;
    /**
     * 媒体类型（仅非目录或相簿返回）
     */
    'contentType'?: string;
    /**
     * 文件大小（仅非目录或相簿返回），字符串格式以避免精度问题
     */
    'size'?: string;
    /**
     * 目录或文件的 ETag
     */
    'eTag'?: string;
    /**
     * 是否被收藏，当 WithFavoriteStatus = 1 时返回
     */
    'isFavorite'?: boolean;
    /**
     * 文件的 CRC64-ECMA182 校验值（仅非目录或相簿返回），字符串格式
     */
    'crc64'?: string;
    /**
     * 版本号（仅非目录或相簿返回）
     */
    'versionId'?: number | null;
    /**
     * 文件元数据信息（仅非目录或相簿返回）
     */
    'metaData'?: { [key: string]: string; };
    /**
     * 是否可通过 wps 预览（仅非目录或相簿返回）
     */
    'previewByDoc'?: boolean;
    /**
     * 是否可通过万象预览（仅非目录或相簿返回）
     */
    'previewByCI'?: boolean;
    /**
     * 是否可用预览图作为 icon（仅非目录或相簿返回）
     */
    'previewAsIcon'?: boolean;
    /**
     * 文件类型：excel、powerpoint 等（仅非目录或相簿返回）
     */
    'fileType'?: string;
    /**
     * 简易文件标签列表
     */
    'labels'?: Array<string>;
    /**
     * 文件自定义的分类，string类型
     */
    'category'?: string;
    /**
     * 符号链接指向的下一级文件的inode，当文件为符号链接时返回
     */
    'linkTo'?: string;
    /**
     * 文件内容的Cas标识
     */
    'contentCas'?: string;
}

export const InfoFileOrDirectory200ResponseTypeEnum = {
    Dir: 'dir',
    File: 'file',
    Image: 'image',
    Video: 'video',
    Symlink: 'symlink',
    Virtual: 'virtual'
} as const;

export type InfoFileOrDirectory200ResponseTypeEnum = typeof InfoFileOrDirectory200ResponseTypeEnum[keyof typeof InfoFileOrDirectory200ResponseTypeEnum];


