/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ListRecentlyUsedFile200ResponseContentsInner {
    /**
     * 文件名
     */
    'name'?: string;
    /**
     * 空间ID
     */
    'spaceId'?: string;
    /**
     * 文件ID
     */
    'inode'?: string;
    /**
     * 文件大小，为了避免数字精度问题，这里为字符串格式
     */
    'size'?: string;
    /**
     * 加入最近使用列表时的操作类型
     */
    'actionType'?: ListRecentlyUsedFile200ResponseContentsInnerActionTypeEnum;
    /**
     * ISO 8601格式的日期与时间字符串，表示加入最近使用文件列表的时间
     */
    'operationTime'?: string;
    /**
     * ISO 8601格式的日期与时间字符串，表示文件的上传时间
     */
    'creationTime'?: string;
    /**
     * 文件的CRC64-ECMA182校验值，为了避免数字精度问题，这里为字符串格式
     */
    'crc64'?: string;
    /**
     * 字符串数组，表示文件的路径，仅当设置了withPath为true时返回该字段
     */
    'path'?: Array<string>;
}

export const ListRecentlyUsedFile200ResponseContentsInnerActionTypeEnum = {
    Preview: 'preview',
    Modify: 'modify'
} as const;

export type ListRecentlyUsedFile200ResponseContentsInnerActionTypeEnum = typeof ListRecentlyUsedFile200ResponseContentsInnerActionTypeEnum[keyof typeof ListRecentlyUsedFile200ResponseContentsInnerActionTypeEnum];


