/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ListHistory200ResponseContentsInner {
    /**
     * 历史版本 ID，最新历史版本不返回这一字段
     */
    'id'?: number;
    /**
     * 创建人 ID
     */
    'createdBy'?: string;
    /**
     * 创建方式，0：创建，1：更新
     */
    'creationWay'?: number;
    /**
     * 版本号
     */
    'version'?: number;
    /**
     * 是否最新版本
     */
    'isLatestVersion'?: boolean;
    /**
     * 目录或相簿名或文件名
     */
    'name'?: string;
    /**
     * 历史版本文件大小
     */
    'size'?: number;
    /**
     * 文件的 CRC64-ECMA182 校验值，为了避免数字精度问题，这里为字符串格式
     */
    'crc64'?: string;
    /**
     * 文件元类型
     */
    'contentType'?: string;
    /**
     * ISO 8601格式的日期与时间字符串，表示文件的创建时间
     */
    'creationTime'?: string;
    /**
     * 设置为最新版本的时间
     */
    'setLatestTime'?: string;
}

