/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ListShareFiles200ResponseContentsInner } from './list-share-files200-response-contents-inner';

export interface ListShareFiles200Response {
    /**
     * 文件/目录列表数组
     */
    'contents'?: Array<ListShareFiles200ResponseContentsInner>;
    /**
     * 分页标记，用于获取下一页，无更多数据时为空字符串
     */
    'marker'?: string;
    /**
     * 是否还有更多数据，true 表示有下一页，false 表示已是最后一页
     */
    'hasMore'?: boolean;
}

