/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ListSpace200ResponseListInner {
    /**
     * 租户空间ID。
     */
    'spaceId'?: string;
    /**
     * 创建者用户ID。
     */
    'userId'?: string;
    /**
     * 租户空间创建时间，ISO 8601格式的日期与时间字符串。
     */
    'creationTime'?: string;
}

