/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ListShareFiles200ResponseContentsInner {
    /**
     * 文件或目录名称
     */
    'name'?: string;
    /**
     * 文件所在空间 ID
     */
    'spaceId'?: string;
    /**
     * 类型，file（文件）或 dir（目录）
     */
    'type'?: ListShareFiles200ResponseContentsInnerTypeEnum;
    /**
     * 文件大小（整数转的字符串），为目录时不返回
     */
    'size'?: string;
    /**
     * ISO 8601格式的日期与时间字符串，最后修改时间
     */
    'updateTime'?: string;
    /**
     * 是否允许预览
     */
    'canPreview'?: boolean;
    /**
     * 是否允许下载
     */
    'canDownload'?: boolean;
    /**
     * 是否允许转存到网盘
     */
    'canSaveToNetdisk'?: boolean;
    /**
     * 文件/目录的 inode 标识，用于下载、预览、访问子目录
     */
    'inode'?: string;
}

export const ListShareFiles200ResponseContentsInnerTypeEnum = {
    File: 'file',
    Dir: 'dir'
} as const;

export type ListShareFiles200ResponseContentsInnerTypeEnum = typeof ListShareFiles200ResponseContentsInnerTypeEnum[keyof typeof ListShareFiles200ResponseContentsInnerTypeEnum];


