/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface PrepareM3u8UploadRequestSegmentsInner {
    /**
     * 分片文件路径，如 1.ts 或 abc/def/1.ts，不能包含特殊字符
     */
    'path'?: string;
    /**
     * 上传类型
     */
    'uploadMethod'?: PrepareM3u8UploadRequestSegmentsInnerUploadMethodEnum;
}

export const PrepareM3u8UploadRequestSegmentsInnerUploadMethodEnum = {
    Simple: 'simple',
    Multipart: 'multipart'
} as const;

export type PrepareM3u8UploadRequestSegmentsInnerUploadMethodEnum = typeof PrepareM3u8UploadRequestSegmentsInnerUploadMethodEnum[keyof typeof PrepareM3u8UploadRequestSegmentsInnerUploadMethodEnum];


