/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 预签名 m3u8 文件上传信息（用于客户端上传至 COS）
 */
export interface PrepareM3u8Upload201ResponsePlaylist {
    /**
     * 实际上传文件时的域名
     */
    'domain'?: string;
    /**
     * 实际分片上传时的 URL 路径
     */
    'path'?: string;
    /**
     * 实际分片上传时需指定的请求头部
     */
    'headers'?: { [key: string]: string; };
    /**
     * 上传信息有效期，失效后需要调用m3u8上传续期接口进行续期
     */
    'expiration'?: string;
}

