/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PrepareM3u8UploadRequestSegmentsInner } from './prepare-m3u8-upload-request-segments-inner';

export interface PrepareM3u8UploadRequest {
    /**
     * 用于秒传的抽样哈希
     */
    'sampleHash'?: string;
    /**
     * 分片数量，字符串类型，与 sampleHash 捆绑传入
     */
    'segmentsCount'?: string;
    /**
     * 播放列表(media playlist)，只支持 media playlist，不支持 master playlist，不支持指定上传方法，固定为简单上传
     */
    'playlist'?: object;
    /**
     * 分片文件名称列表(包含可选的密钥)，限定长度为100（传密钥时限定长度为101），很长时需要分批调用m3u8 分片重传与追加接口进行追加
     */
    'segments'?: Array<PrepareM3u8UploadRequestSegmentsInner>;
}

