/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 树形结构（format=tree 时）
 */
export interface PreviewZipFile200ResponseContentsOneOf {
    /**
     * 目录层级深度，根节点为 0
     */
    'level'?: number;
    /**
     * 是否是文件夹
     */
    'isDir'?: boolean;
    /**
     * 文件或文件夹名（不含路径前缀）
     */
    'filename'?: string;
    /**
     * 上一级目录名
     */
    'prename'?: string;
    /**
     * 上一级目录前缀分隔符
     */
    'prefix'?: string;
    /**
     * 文件在压缩包内的完整路径（仅文件节点有值），该路径可用于选择性解压的 selectedFilePaths 参数
     */
    'key'?: string;
    /**
     * 最后修改时间（ISO 8601 格式），仅文件节点有值
     */
    'lastModified'?: string;
    /**
     * 文件解压后大小（字节），仅文件节点有值
     */
    'uncompressedSize'?: number;
    /**
     * 子文件/文件夹信息数组，文件夹排在文件前面；文件节点该字段为 null
     */
    'children'?: Array<object> | null;
}

