/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PreviewZipFile200ResponseContents } from './preview-zip-file200-response-contents';

export interface PreviewZipFile200Response {
    /**
     * 压缩包中文件/文件夹数量
     */
    'fileNumber'?: number;
    /**
     * 是否被截断，压缩包预览最多支持预览前 1000 个文件
     */
    'isTruncated'?: boolean;
    'contents'?: PreviewZipFile200ResponseContents;
}

