/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface QueryLibraryTask200ResponseInner {
    /**
     * 任务 ID
     */
    'taskId'?: number;
    /**
     * 任务状态码，202: 任务进行中，200: 任务成功完成且有返回结果，返回结果在 result 字段中，204: 任务成功完成且无返回结果，500: 任务执行失败
     */
    'status'?: number;
    /**
     * 任务成功完成后的返回结果
     */
    'result'?: object;
}

