/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { QueryLibraryTaskV2200ResponseClearLibraryHistoryResult } from './query-library-task-v2200-response-clear-library-history-result';

export interface QueryLibraryTaskV2200Response {
    /**
     * 任务唯一标识符
     */
    'taskId'?: string;
    /**
     * 任务类型标识，用于 SDK 根据类型解析对应的结果结构
     */
    'taskType'?: QueryLibraryTaskV2200ResponseTaskTypeEnum;
    /**
     * 任务状态码，202: 处理中，200: 成功，500: 任务失败
     */
    'status'?: number;
    'clearLibraryHistoryResult'?: QueryLibraryTaskV2200ResponseClearLibraryHistoryResult;
}

export const QueryLibraryTaskV2200ResponseTaskTypeEnum = {
    ClearLibraryHistory: 'clearLibraryHistory'
} as const;

export type QueryLibraryTaskV2200ResponseTaskTypeEnum = typeof QueryLibraryTaskV2200ResponseTaskTypeEnum[keyof typeof QueryLibraryTaskV2200ResponseTaskTypeEnum];


