/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { QueryTaskV2200ResponseBatchCopyResultsInner } from './query-task-v2200-response-batch-copy-results-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { QueryTaskV2200ResponseBatchDeleteResultsInner } from './query-task-v2200-response-batch-delete-results-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { QueryTaskV2200ResponseBatchMoveResultsInner } from './query-task-v2200-response-batch-move-results-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { QueryTaskV2200ResponseBatchRestoreRecycleResultsInner } from './query-task-v2200-response-batch-restore-recycle-results-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { QueryTaskV2200ResponseCalibrateDirectoryStatsResult } from './query-task-v2200-response-calibrate-directory-stats-result';
// May contain unused imports in some cases
// @ts-ignore
import type { QueryTaskV2200ResponseConvertFileResult } from './query-task-v2200-response-convert-file-result';
// May contain unused imports in some cases
// @ts-ignore
import type { QueryTaskV2200ResponseFileUncompressResult } from './query-task-v2200-response-file-uncompress-result';

export interface QueryTaskV2200Response {
    /**
     * 任务唯一标识符
     */
    'taskId'?: string;
    /**
     * 任务类型标识，用于 SDK 根据类型解析对应的结果结构
     */
    'taskType'?: QueryTaskV2200ResponseTaskTypeEnum;
    /**
     * 任务状态码，202: 处理中，200: 成功，207: 部分成功，400: 全部失败，500: 任务失败
     */
    'status'?: number;
    /**
     * 批量移动任务结果（taskType 为 batchMove 时返回）
     */
    'batchMoveResults'?: Array<QueryTaskV2200ResponseBatchMoveResultsInner>;
    /**
     * 批量复制任务结果（taskType 为 batchCopy 时返回）
     */
    'batchCopyResults'?: Array<QueryTaskV2200ResponseBatchCopyResultsInner>;
    /**
     * 批量删除任务结果（taskType 为 batchDelete 时返回）
     */
    'batchDeleteResults'?: Array<QueryTaskV2200ResponseBatchDeleteResultsInner>;
    /**
     * 批量恢复回收站任务结果（taskType 为 batchRestoreRecycle 时返回）
     */
    'batchRestoreRecycleResults'?: Array<QueryTaskV2200ResponseBatchRestoreRecycleResultsInner>;
    'convertFileResult'?: QueryTaskV2200ResponseConvertFileResult;
    'calibrateDirectoryStatsResult'?: QueryTaskV2200ResponseCalibrateDirectoryStatsResult;
    /**
     * 视频转码任务结果（taskType 为 videoTranscode 时返回），结构待扩展
     */
    'videoTranscodeResult'?: object;
    'fileUncompressResult'?: QueryTaskV2200ResponseFileUncompressResult;
}

export const QueryTaskV2200ResponseTaskTypeEnum = {
    BatchMove: 'batchMove',
    BatchCopy: 'batchCopy',
    BatchDelete: 'batchDelete',
    BatchRestoreRecycle: 'batchRestoreRecycle',
    ConvertFile: 'convertFile',
    CalibrateDirectoryStats: 'calibrateDirectoryStats',
    VideoTranscode: 'videoTranscode',
    FileUncompress: 'fileUncompress'
} as const;

export type QueryTaskV2200ResponseTaskTypeEnum = typeof QueryTaskV2200ResponseTaskTypeEnum[keyof typeof QueryTaskV2200ResponseTaskTypeEnum];


