/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface QueryDeltaLog200ResponseContentsInner {
    /**
     * 事件类型，可能的取值： - FILE.CREATE: 文件/目录/软链接创建（包括上传完成、秒传、目录创建、软链接创建） - FILE.MODIFY: 文件内容修改（包括文件内容更新、覆盖上传） - FILE.DELETE: 文件彻底删除（非回收站删除） - FILE.COPY: 文件/目录复制 - FILE.MOVE: 文件/目录移动（含重命名） - FILE.TRASH: 文件/目录放入回收站 - FILE.RESTORE: 文件/目录从回收站恢复 - FILE.CREATE_OVERWRITE: 创建文件时覆盖已有文件 - FILE.MOVE_OVERWRITE: 移动文件时覆盖已有文件 - FILE.COPY_OVERWRITE: 拷贝文件时覆盖已有文件 - FILE.RESTORE_OVERWRITE: 从回收站恢复时覆盖已有文件 - TASK.FILE.DELETE: 系统任务触发的文件彻底删除 - TASK.FILE.TRASH: 系统任务触发的放入回收站操作 - TASK.FILE.RESTORE: 系统任务触发的从回收站恢复操作 - RECYCLE.DELETE: 从回收站彻底删除 - RECYCLE.MODIFY: 回收站项目信息更新 - HISTORY.CREATE: 历史版本创建 - HISTORY.DELETE: 历史版本删除 - HISTORY.LATEST: 设为最新版本（回滚到指定历史版本） - HISTORY.MODIFY: 历史版本更新 
     */
    'eventType'?: QueryDeltaLog200ResponseContentsInnerEventTypeEnum;
    /**
     * 事件发生时间（精确到毫秒），ISO 8601 格式
     */
    'eventTime'?: string;
    /**
     * 文件/目录的唯一标识 ID
     */
    'inode'?: string;
    /**
     * 父目录的唯一标识 ID
     */
    'parentInode'?: string;
    /**
     * 文件名或目录名
     */
    'name'?: string;
    /**
     * 节点类型：file-文件，dir-目录，symlink-符号链接
     */
    'type'?: QueryDeltaLog200ResponseContentsInnerTypeEnum;
    /**
     * 文件大小，为了避免数字精度问题，这里为字符串格式（仅文件类型返回）
     */
    'size'?: string;
    /**
     * 文件 ETag（仅文件类型返回）
     */
    'eTag'?: string;
    /**
     * 文件的 CRC64-ECMA182 校验值，为了避免数字精度问题，这里为字符串格式（仅文件类型返回）
     */
    'crc64'?: string;
    /**
     * 媒体类型（仅文件类型返回）
     */
    'contentType'?: string;
    /**
     * 文件自定义分类，如 image、video、document 等（仅文件类型返回）
     */
    'category'?: string;
    /**
     * 文件类型：excel、powerpoint、word、image 等（仅文件类型返回）
     */
    'fileType'?: string;
    /**
     * 文件的创建时间或上传时间
     */
    'creationTime'?: string;
    /**
     * 文件最近一次被覆盖的时间，或者目录内最近一次增删子目录或文件的时间
     */
    'modificationTime'?: string;
    /**
     * 文件对应的本地创建时间（仅文件类型返回）
     */
    'localCreationTime'?: string;
    /**
     * 文件对应的本地修改时间（仅文件类型返回）
     */
    'localModificationTime'?: string;
    /**
     * 操作者用户 ID
     */
    'userId'?: string;
    /**
     * 版本号（仅文件类型返回）
     */
    'versionId'?: number;
    /**
     * 文件位置：0-普通文件/目录，位于正常目录树中；1-回收站中的文件/目录；2-历史版本文件；3-已标记删除的普通文件（软删除）
     */
    'location'?: QueryDeltaLog200ResponseContentsInnerLocationEnum;
    /**
     * 是否被配额策略删除标记
     */
    'removedByQuota'?: boolean;
    /**
     * 软链接指向的目标文件 inode（仅软链接类型返回，普通文件为空）
     */
    'linkTo'?: string;
    /**
     * 额外信息，不同事件类型携带不同的扩展信息： - FILE.CREATE 事件：isRapidUpload（布尔值，是否为秒传创建）；软链接创建时包含 targetInode（字符串，软链接指向的目标 inode） - FILE.MODIFY 事件：oldSize（整数，修改前文件大小）、newSize（整数，修改后文件大小）、oldEtag（字符串，修改前文件 ETag） - FILE.COPY 事件：sourceInode（字符串，复制源文件/目录的 inode） - FILE.MOVE 事件：fromParentInode（字符串，移动前的父目录 inode）、toParentInode（字符串，移动后的父目录 inode）；跨空间移动时还包含 fromLibraryId 和 fromSpaceId - FILE.*_OVERWRITE 事件：保留原事件类型的 extraInfo 字段，额外包含被覆盖文件信息：owInode、owSize、owEtag、owCRC64、owContentType、owRevisionVersion - HISTORY.CREATE 事件：versionId（字符串，历史版本标识） - HISTORY.LATEST 事件：owInode、owSize、owEtag、owCRC64、owContentType、owRevisionVersion（被覆盖文件信息） - 其他事件：null 或空对象 
     */
    'extraInfo'?: { [key: string]: any; } | null;
}

export const QueryDeltaLog200ResponseContentsInnerEventTypeEnum = {
    FileCreate: 'FILE.CREATE',
    FileModify: 'FILE.MODIFY',
    FileDelete: 'FILE.DELETE',
    FileCopy: 'FILE.COPY',
    FileMove: 'FILE.MOVE',
    FileTrash: 'FILE.TRASH',
    FileRestore: 'FILE.RESTORE',
    FileCreateOverwrite: 'FILE.CREATE_OVERWRITE',
    FileMoveOverwrite: 'FILE.MOVE_OVERWRITE',
    FileCopyOverwrite: 'FILE.COPY_OVERWRITE',
    FileRestoreOverwrite: 'FILE.RESTORE_OVERWRITE',
    TaskFileDelete: 'TASK.FILE.DELETE',
    TaskFileTrash: 'TASK.FILE.TRASH',
    TaskFileRestore: 'TASK.FILE.RESTORE',
    RecycleDelete: 'RECYCLE.DELETE',
    RecycleModify: 'RECYCLE.MODIFY',
    HistoryCreate: 'HISTORY.CREATE',
    HistoryDelete: 'HISTORY.DELETE',
    HistoryLatest: 'HISTORY.LATEST',
    HistoryModify: 'HISTORY.MODIFY'
} as const;

export type QueryDeltaLog200ResponseContentsInnerEventTypeEnum = typeof QueryDeltaLog200ResponseContentsInnerEventTypeEnum[keyof typeof QueryDeltaLog200ResponseContentsInnerEventTypeEnum];
export const QueryDeltaLog200ResponseContentsInnerTypeEnum = {
    File: 'file',
    Dir: 'dir',
    Symlink: 'symlink'
} as const;

export type QueryDeltaLog200ResponseContentsInnerTypeEnum = typeof QueryDeltaLog200ResponseContentsInnerTypeEnum[keyof typeof QueryDeltaLog200ResponseContentsInnerTypeEnum];
export const QueryDeltaLog200ResponseContentsInnerLocationEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;

export type QueryDeltaLog200ResponseContentsInnerLocationEnum = typeof QueryDeltaLog200ResponseContentsInnerLocationEnum[keyof typeof QueryDeltaLog200ResponseContentsInnerLocationEnum];


