/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 实际上传时需指定的请求头部
 */
export interface RenewMultipartUpload200ResponseHeaders {
    'Content-Type'?: string;
    'Authorization'?: string;
    'x-cos-security-token'?: string;
    'x-cos-traffic-limit'?: string;
}

