/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SearchShares200ResponseContentsInner {
    /**
     * 分享 ID
     */
    'id'?: string;
    /**
     * 分享名称
     */
    'name'?: string;
    /**
     * 创建时间
     */
    'createTime'?: string;
    /**
     * 过期时间
     */
    'expireTime'?: string;
    /**
     * 管理员是否启用
     */
    'adminEnabled'?: boolean;
    /**
     * 创建者是否启用
     */
    'ownerEnabled'?: boolean;
    /**
     * 是否为永久分享
     */
    'isPermanent'?: boolean;
    /**
     * 是否允许预览
     */
    'canPreview'?: boolean;
    /**
     * 是否允许下载
     */
    'canDownload'?: boolean;
    /**
     * 是否允许保存到网盘
     */
    'canSaveToNetdisk'?: boolean;
    /**
     * 预览次数限制（canPreview 为 false 时返回 0）
     */
    'previewLimit'?: number;
    /**
     * 已使用的预览次数
     */
    'previewUsed'?: number;
    /**
     * 下载次数限制（canDownload 为 false 时返回 0）
     */
    'downloadLimit'?: number;
    /**
     * 已使用的下载次数
     */
    'downloadUsed'?: number;
    /**
     * 分享状态：0-未审核、1-审核中、2-审核通过、3-审核不通过
     */
    'status'?: SearchShares200ResponseContentsInnerStatusEnum;
    /**
     * 访问用户数限制
     */
    'userLimit'?: number;
    /**
     * 已访问的用户数
     */
    'userLimitUsed'?: number;
    /**
     * 分享的提取码（没有提取码则为空）
     */
    'code'?: string;
    /**
     * 创建者 ID
     */
    'creatorId'?: string;
}

export const SearchShares200ResponseContentsInnerStatusEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;

export type SearchShares200ResponseContentsInnerStatusEnum = typeof SearchShares200ResponseContentsInnerStatusEnum[keyof typeof SearchShares200ResponseContentsInnerStatusEnum];


