/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SearchAI200ResponseContentsInner {
    /**
     * 命中文件的 inode，两种 type 均返回
     */
    'inode'?: string;
    /**
     * 服务端计算的语义匹配得分，整数，分数越高越相关，两种 type 均返回
     */
    'score'?: number;
    /**
     * 命中文档片段（字符串），仅 type=text 返回
     */
    'text'?: string;
    /**
     * 命中片段所在页码（整数），仅 type=text 返回；PDF/DOCX/PPTX 等有分页的文档才有意义，纯文本类文档为 0
     */
    'textPage'?: number;
}

