/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SearchFsStatsRequestAggregationsInnerSubAggregationsInner } from './search-fs-stats-request-aggregations-inner-sub-aggregations-inner';

export interface SearchFsStatsRequestAggregationsInner {
    /**
     * 聚合字段名，必选参数
     */
    'field': SearchFsStatsRequestAggregationsInnerFieldEnum;
    /**
     * 聚合操作，必选参数
     */
    'operation': SearchFsStatsRequestAggregationsInnerOperationEnum;
    /**
     * 子聚合数组，可选参数，仅当 operation 为 group 时有效，用于对每个分组进行进一步统计，最多 3 个子聚合项。子聚合操作不支持 group（即不支持多层嵌套分组）。
     */
    'subAggregations'?: Array<SearchFsStatsRequestAggregationsInnerSubAggregationsInner>;
}

export const SearchFsStatsRequestAggregationsInnerFieldEnum = {
    ExtName: 'extName',
    Category: 'category',
    Size: 'size',
    ContentType: 'contentType',
    UserId: 'userId',
    Name: 'name',
    FileType: 'fileType'
} as const;

export type SearchFsStatsRequestAggregationsInnerFieldEnum = typeof SearchFsStatsRequestAggregationsInnerFieldEnum[keyof typeof SearchFsStatsRequestAggregationsInnerFieldEnum];
export const SearchFsStatsRequestAggregationsInnerOperationEnum = {
    Group: 'group',
    Count: 'count',
    Distinct: 'distinct',
    Sum: 'sum',
    Min: 'min',
    Max: 'max',
    Average: 'average'
} as const;

export type SearchFsStatsRequestAggregationsInnerOperationEnum = typeof SearchFsStatsRequestAggregationsInnerOperationEnum[keyof typeof SearchFsStatsRequestAggregationsInnerOperationEnum];


