/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SearchFs200ResponseContentsInnerContentHighlight } from './search-fs200-response-contents-inner-content-highlight';

export interface SearchFs200ResponseContentsInner {
    /**
     * 条目类型：dir-目录或相簿；file-文件，仅用于文件类型媒体库；image-图片，仅用于媒体类型媒体库；video-视频，仅用于媒体类型媒体库；symlink-符号链接
     */
    'type'?: SearchFs200ResponseContentsInnerTypeEnum;
    /**
     * 文件或目录 ID（查询时需带 with_inode=1 才会返回）
     */
    'inode'?: string;
    /**
     * 目录名或文件名
     */
    'name'?: string;
    /**
     * ISO 8601格式的日期与时间字符串，表示目录/相簿的创建时间或文件的上传时间
     */
    'creationTime'?: string;
    /**
     * 文件最近一次被覆盖的时间，或目录内最近一次增删子目录/文件的时间
     */
    'modificationTime'?: string;
    /**
     * 媒体类型，仅 file 类型返回
     */
    'contentType'?: string;
    /**
     * 版本号，仅 file 类型返回
     */
    'versionId'?: number;
    /**
     * 文件大小，字符串格式避免数字精度问题，仅 file 类型返回
     */
    'size'?: string;
    /**
     * 是否被当前用户收藏，仅当请求带 with_favorite_status=1 时返回；仅 type=filename 生效，type=filecontent 不返回此字段
     */
    'isFavorite'?: boolean;
    /**
     * 文件 ETag，仅 file 类型返回
     */
    'eTag'?: string;
    /**
     * 文件的 CRC64-ECMA182 校验值，字符串格式，仅 file 类型返回
     */
    'crc64'?: string;
    /**
     * 文件元数据信息，仅 file 类型返回
     */
    'metaData'?: { [key: string]: string; };
    /**
     * 创建/更新者用户 ID
     */
    'userId'?: string;
    /**
     * 是否可通过 wps 预览
     */
    'previewByDoc'?: boolean;
    /**
     * 是否可通过万象预览
     */
    'previewByCI'?: boolean;
    /**
     * 是否可使用预览图当做 icon
     */
    'previewAsIcon'?: boolean;
    /**
     * 文件类别，如 doc/image/video/archive 等
     */
    'fileType'?: string;
    /**
     * 简易文件标签数组
     */
    'labels'?: Array<string>;
    /**
     * 自定义文件分类，比如 image、video、doc 等
     */
    'category'?: string;
    /**
     * 文件对应的本地创建时间
     */
    'localCreationTime'?: string;
    /**
     * 文件对应的本地修改时间
     */
    'localModificationTime'?: string;
    /**
     * 命中的正文片段，仅 type=filecontent 返回
     */
    'text'?: string;
    /**
     * 命中片段所在文档页码（整数），仅 type=filecontent 返回；PDF/DOCX/PPTX 等有分页的文档才有意义，纯文本类文档为 0
     */
    'textPage'?: number;
    /**
     * 服务端计算的匹配得分（分数越高越相关），仅 type=filecontent 返回
     */
    'searchScore'?: number;
    'contentHighlight'?: SearchFs200ResponseContentsInnerContentHighlight;
}

export const SearchFs200ResponseContentsInnerTypeEnum = {
    Dir: 'dir',
    File: 'file',
    Image: 'image',
    Video: 'video',
    Symlink: 'symlink'
} as const;

export type SearchFs200ResponseContentsInnerTypeEnum = typeof SearchFs200ResponseContentsInnerTypeEnum[keyof typeof SearchFs200ResponseContentsInnerTypeEnum];


