/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SearchFsStatsRequestAggregationsInnerSubAggregationsInner {
    /**
     * 子聚合字段名，必选参数
     */
    'field': SearchFsStatsRequestAggregationsInnerSubAggregationsInnerFieldEnum;
    /**
     * 子聚合操作，必选参数，不支持 group
     */
    'operation': SearchFsStatsRequestAggregationsInnerSubAggregationsInnerOperationEnum;
}

export const SearchFsStatsRequestAggregationsInnerSubAggregationsInnerFieldEnum = {
    ExtName: 'extName',
    Category: 'category',
    Size: 'size',
    ContentType: 'contentType',
    UserId: 'userId',
    Name: 'name',
    FileType: 'fileType'
} as const;

export type SearchFsStatsRequestAggregationsInnerSubAggregationsInnerFieldEnum = typeof SearchFsStatsRequestAggregationsInnerSubAggregationsInnerFieldEnum[keyof typeof SearchFsStatsRequestAggregationsInnerSubAggregationsInnerFieldEnum];
export const SearchFsStatsRequestAggregationsInnerSubAggregationsInnerOperationEnum = {
    Count: 'count',
    Distinct: 'distinct',
    Sum: 'sum',
    Min: 'min',
    Max: 'max',
    Average: 'average'
} as const;

export type SearchFsStatsRequestAggregationsInnerSubAggregationsInnerOperationEnum = typeof SearchFsStatsRequestAggregationsInnerSubAggregationsInnerOperationEnum[keyof typeof SearchFsStatsRequestAggregationsInnerSubAggregationsInnerOperationEnum];


