/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SearchFsRequest {
    /**
     * 搜索子模式，取值 filename（基础检索，按文件名命中）或 filecontent（全文关键字检索，按文件正文内容命中）；默认 filename
     */
    'type'?: SearchFsRequestTypeEnum;
    /**
     * 搜索关键字，可选参数，字符串数组（元素间为\"或\"关系），数组长度上限 100；type=filename 下按文件名命中，不做停用词过滤；type=filecontent 下按文件正文内容全文检索，服务端会自动过滤停用词
     */
    'keywords'?: Array<string>;
    /**
     * 搜索范围，指定搜索的目录，可选参数，如搜索根目录可指定为空字符串、\"/\"或不指定该字段；type=filecontent 下路径匹配能力有限，建议不填
     */
    'scope'?: string;
    /**
     * 包含的搜索文件后缀，可选参数，字符串数组，或的关系，数组长度上限 20，单元素 rune 长度上限 10
     */
    'inExtnames'?: Array<string>;
    /**
     * 不包含的搜索文件后缀，可选参数，字符串数组，与的关系，数组长度上限 20，单元素 rune 长度上限 10
     */
    'excludeExtnames'?: Array<string>;
    /**
     * 文件类型，可选参数，字符串数组，取值 all/dir/file/symlink，或的关系
     */
    'fileTypes'?: Array<SearchFsRequestFileTypesEnum>;
    /**
     * 搜索文件大小范围，整数，单位 Byte，可选参数；若 minFileSize > maxFileSize 返回 HTTP 4xx
     */
    'minFileSize'?: number;
    /**
     * 搜索文件大小范围，整数，单位 Byte，可选参数
     */
    'maxFileSize'?: number;
    /**
     * 搜索更新时间范围，RFC3339 格式字符串，可选参数；若起始时间晚于结束时间返回 HTTP 4xx
     */
    'modificationTimeStart'?: string;
    /**
     * 搜索更新时间范围，RFC3339 格式字符串，可选参数
     */
    'modificationTimeEnd'?: string;
    /**
     * 排序字段，可选参数；当前版本暂不支持按字段排序，字段传入不会报错但实际无效
     */
    'orderBy'?: SearchFsRequestOrderByEnum;
    /**
     * 排序方式，升序为 asc，降序为 desc，可选参数；当前版本暂不支持，字段传入不会报错但实际无效
     */
    'orderByType'?: SearchFsRequestOrderByTypeEnum;
    /**
     * 简易文件标签，可选参数，字符串数组，或的关系，数组长度上限 20，单元素 rune 长度上限 32
     */
    'labels'?: Array<string>;
    /**
     * 文件自定义分类，可选参数，字符串数组，或的关系，数组长度上限 20，取值必须属于该媒体库已声明的类目集合
     */
    'categories'?: Array<string>;
    /**
     * 用于顺序列出分页的标识，可选参数
     */
    'marker'?: string;
}

export const SearchFsRequestTypeEnum = {
    Filename: 'filename',
    Filecontent: 'filecontent'
} as const;

export type SearchFsRequestTypeEnum = typeof SearchFsRequestTypeEnum[keyof typeof SearchFsRequestTypeEnum];
export const SearchFsRequestFileTypesEnum = {
    All: 'all',
    Dir: 'dir',
    File: 'file',
    Symlink: 'symlink'
} as const;

export type SearchFsRequestFileTypesEnum = typeof SearchFsRequestFileTypesEnum[keyof typeof SearchFsRequestFileTypesEnum];
export const SearchFsRequestOrderByEnum = {
    Name: 'name',
    ModificationTime: 'modificationTime',
    Size: 'size',
    CreationTime: 'creationTime',
    LocalCreationTime: 'localCreationTime',
    LocalModificationTime: 'localModificationTime'
} as const;

export type SearchFsRequestOrderByEnum = typeof SearchFsRequestOrderByEnum[keyof typeof SearchFsRequestOrderByEnum];
export const SearchFsRequestOrderByTypeEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type SearchFsRequestOrderByTypeEnum = typeof SearchFsRequestOrderByTypeEnum[keyof typeof SearchFsRequestOrderByTypeEnum];


