/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SetSpaceTrafficLimitRequest {
    /**
     * 空间下载限速，范围100KB/s-100MB/s，单位Byte，输入-1表示取消限速
     */
    'downloadTrafficLimit': number;
}

