/* tslint:disable */
/* eslint-disable */
/**
 * 腾讯云智能媒资托管服务API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 分享配置对象，必选参数
 */
export interface UpdateShareRequestConfig {
    /**
     * 是否永久有效，可选参数，默认为 false；当为 false 时，expireTime 必选
     */
    'isPermanent'?: boolean;
    /**
     * 过期时间，ISO 8601 格式，当 isPermanent 为 false 时必选
     */
    'expireTime'?: string;
    /**
     * 提取码，可选参数（6位以下）
     */
    'extractionCode'?: string;
    /**
     * 是否允许预览，可选参数，默认为 false
     */
    'canPreview'?: boolean;
    /**
     * 是否允许下载，可选参数，默认为 false
     */
    'canDownload'?: boolean;
    /**
     * 是否允许保存到网盘，可选参数，默认为 false
     */
    'canSaveToNetdisk'?: boolean;
    /**
     * 是否禁止匿名用户访问，可选参数，默认为 false
     */
    'forbidAnonymousUser'?: boolean;
    /**
     * 预览次数限制，可选参数（如果 canPreview 为 false，忽略此参数）
     */
    'previewLimit'?: number;
    /**
     * 下载次数限制，可选参数（canDownload 为 false 时，忽略此参数）
     */
    'downloadLimit'?: number;
    /**
     * 访问用户数限制，可选参数（设置时禁止匿名用户访问，冲突报错）
     */
    'userLimit'?: number;
}

